### ISSUE TITLE
Install fail on Ubuntu

### ISSUE THREAD

**Issue by yasminlucero** [wesm/feather#103]
```feather/metadata.cc: In constructor ‘feather::metadata::TableBuilder::TableBuilder()’:
feather/metadata.cc:181:5: error: type ‘feather::metadata::TableBuilder’ is not a direct base of ‘feather::metadata::TableBuilder’
make: *** [feather/metadata.o] Error 1
ERROR: compilation failed for package ‘feather’```

My system: 
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)
```

and Rcpp_0.12.4

**Comment by thirdwing** [comment]
Which version of GCC are you using?

It might lack C++11 support. Just a guess.

**Comment by yasminlucero** [comment]
We have gcc 4.6 in our environment. Based on this, it may have 0x support if I pass some build parameters, such as this: 

-std=c++11  or -std=gnu++11

```GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard, previously known as C++0x.

This mode can be selected with the -std=c++11 command-line flag, or -std=gnu++11 to enable GNU extensions as well.

For information about C++11 support in a specific version of GCC, please see:

GCC 4.3 C++0x Status
GCC 4.4 C++0x Status
GCC 4.5 C++0x Status
GCC 4.6 C++0x Status
GCC 4.7 C++11 Status
GCC 4.8 C++11 Status

[1:28] 
from: https://gcc.gnu.org/projects/cxx-status.html#cxx11```

**Comment by wesm** [comment]
You will have to use gcc 4.7 or higher (4.8 or higher preferred) to build Feather. I am not sure about the glibc ABI requirements; you may need to rebuild your R toolchain from source using the newer compiler.

We have no plans to support C++0x or earlier versions of gcc at the moment, unless a C++ contributor comes forward with a commitment to help going forward (I work on exclusively C++11/14 projects now so this has little benefit for me personally).

**Comment by yasminlucero** [comment]
makes sense, thanks.
