### ISSUE TITLE
C API and column types other than PRIMITIVE

### ISSUE THREAD

**Issue by dmbates** [wesm/feather#106]
The C API defines types like `feather_category_t` and `feather_category_data_t` but I don't see where they are used in the API.  I am trying to read feather files with categories and can't decide how to take the column apart using the C API.

Also the header file defines several functions like `feather_writer_append_category`, `feather_writer_append_timestamp`, etc. but the only one with an implementation is `feather_writer_append_plain`.

**Comment by ScottPJones** [comment]
I think that's a known limitation at the moment: see the comment from @wesm: https://github.com/wesm/feather/pull/96#issuecomment-205165292

**Comment by dmbates** [comment]
I see that in the C++ API a `CategoryColumn` extends `Column` adding a member of type `CategoryMetadata`.  I'm not exactly sure what the corresponding C structures would look like.

**Comment by wesm** [comment]
The category and other structs aren't complete, so don't view them as set in stone! =) 

I think the best way is to allocate a struct on the heap and put it in the `type_metadata` slot:

https://github.com/wesm/feather/blob/master/cpp/src/feather/feather-c.h#L112

So you can do:

```C
if (col->type == FEATHER_COLUMN_CATEGORY) {
  feather_category_data_t metadata = (feather_category_data_t*) col->type_metadata;
}
```

You'll have to put a corresponding `free` in `feather_column_free`.

**Comment by wesm** [comment]
(Be sure to add unit tests to `c-api-test.cc`)

**Comment by wesm** [comment]
I've been on vacation the last 2 weeks, but I can add these C API wrappers soon if no one else has been working on them? Thanks

**Comment by wesm** [comment]
This is superseded by Feather V2 (coming in Arrow 0.17.0) which exactly uses the Arrow IPC file format internally
