### ISSUE TITLE
Factor/categorical levels getting shuffled around?

### ISSUE THREAD

**Issue by sandeep-n** [wesm/feather#108]
Using R magic in a Jupyter notebook on Ubuntu (Python 3.5.1, pandas 0.17.1, R 3.2.4). The species values seem to be getting shuffled around. 

```python
%%R 
> head(iris)
```

      Sepal.Length Sepal.Width Petal.Length Petal.Width Species
    1          5.1         3.5          1.4         0.2  setosa
    2          4.9         3.0          1.4         0.2  setosa
    3          4.7         3.2          1.3         0.2  setosa
    4          4.6         3.1          1.5         0.2  setosa
    5          5.0         3.6          1.4         0.2  setosa
    6          5.4         3.9          1.7         0.4  setosa

```python
%%R
str(iris)
# Species variable stored as factor, not string
```

    'data.frame':	150 obs. of  5 variables:
     $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
     $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
     $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
     $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
     $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

```python
%%R
## Write R dataframe to disk
> write_feather(iris, 'iris.feather')
```

```python
## Read into a pandas dataframe
> iris_pd = feather.read_dataframe('iris.feather')
```

```python
> print(iris_pd.head())
```
       Petal.Length  Petal.Width  Sepal.Length  Sepal.Width     Species
    0           1.4          0.2           5.1          3.5  versicolor
    1           1.4          0.2           4.9          3.0  versicolor
    2           1.3          0.2           4.7          3.2  versicolor
    3           1.5          0.2           4.6          3.1  versicolor
    4           1.4          0.2           5.0          3.6  versicolor

```python

> pd_iris.dtypes
```
    Petal.Length     float64
    Petal.Width      float64
    Sepal.Length     float64
    Sepal.Width      float64
    Species         category
    dtype: object

**Comment by wesm** [comment]
Well, this isn't that great! Are R's factor codes 1-indexed (@hadley)?

**Comment by krlmlr** [comment]
Factors in R start at 1. From R's perspective, the roundtrip seems to work correctly, though: https://github.com/wesm/feather/blob/9b5d6a9c8dc28cb2b54c697a25065cdcbeda997c/R/tests/testthat/test-class.R#L20

**Comment by wesm** [comment]
Right, because the data is not being modified by libfeather. Starting at 1 is out of spec, though (anything ordinal needs to start at 0). Can we patch the R implementation to subtract 1 on write and add 1 on read? Probably also a good time to add a version number to the flatbuffers metadata so we can raise errors on old Feather files.

**Comment by hadley** [comment]
Yeah, that sounds like the right fix to me.

**Comment by wesm** [comment]
I will try to fix this myself if no one has started already -- this is actually a pretty good time to set up some integration testing tools (to check data generated by R code in Python and vice versa). Sound good?

**Comment by hadley** [comment]
Sounds good! (R talks too boring for you? :stuck_out_tongue:)

**Comment by wesm** [comment]
Heh, well, I'll have a little downtime tomorrow when there aren't talks happening. Talking about Feather and friends in about an hour =)
