### ISSUE TITLE
Do people want a feather mailing list?

### ISSUE THREAD

**Issue by wesm** [wesm/feather#112]
We can make technical decisions about Feather on here, or on a mailing list. What would folks prefer?

**Comment by brainstorm** [comment]
I would say that the least time consuming would be to open a google group:

https://groups.google.com/

**Comment by phillc73** [comment]
Or Gitter for extra shiny new thing cool:

https://gitter.im/

**Comment by wesm** [comment]
And here you have it: https://groups.google.com/forum/#!forum/feather-format
