### ISSUE TITLE
[feature request] can read_feather in R use skip?

### ISSUE THREAD

**Issue by jeffwong-nflx** [wesm/feather#115]
I have a feature request for R's read_feather to be able to use the "skip" parameter found in read.csv. Normally when I write data to disk I also write comments for myself for how the data was generated and place them into the csv file. When reading this data back into R later on I use read.csv(..., skip = X). Will I be able to do the same with feather?

The resulting csv I would write would look like

    #Note to self, this file came from ...
    <<normal csv header>>
    <<normal csv row>>

**Comment by hadley** [comment]
No, because feather doesn't support comments in that way.
