### ISSUE TITLE
Add test for NA factor values in R

### ISSUE THREAD

**Issue by wesm** [wesm/feather#117]
follow up to #113, cc @hadley @krlmlr

**Comment by hadley** [comment]
Note that there are two ways of storing NAs as factors in R - they can either go in the levels or in the values:

```R
f1 <- factor(c("a", NA))
unclass(f1)
attributes(f1)

f2 <- addNA(f1)
unclass(f2)
attributes(f2)
```

I have a vague memory of writing tests for both cases, but I might be confused with another project

**Comment by krlmlr** [comment]
There is a [roundtrip test](https://github.com/wesm/feather/blob/364e6b4e2ca1daea13a43bc248a2d58a054ce652/R/tests/testthat/test-roundtrip-vector.R#L64-L70) for both cases.

R has a notion of ordered factors, identical storage format but the order of the levels has a meaning. Is there a way to map this to feather storage?

**Comment by wesm** [comment]
The issue is actually whether R's implementation is robust to data generated by other languages. Let me look a bit closer and I'll see if I can spot any issues.

**Comment by cronacronis** [comment]
Just in case [Representation of numerical NA's in R](http://www.markvanderloo.eu/yaRb/2012/07/08/representation-of-numerical-nas-in-r-and-the-1954-enigma/)

**Comment by wesm** [comment]
Superseded by work in `arrow` which does test for this
