### ISSUE TITLE
NotImplementedError : 3 when importing feather to Python

### ISSUE THREAD

**Issue by einheitActual** [wesm/feather#120]
# Environment
* OSX 10.11.4
* R 0.99.892
* Python 2.7.11

## What I'm trying to do
Load .rds file into R
Write to a feather
Import into Pandas
___
## What's working
df <- readRDS(file, path)
write_feather(df, path)
___
## What's not working
df = feather.read_dataframe(path)
___
## Actual Code
```R
library(feather)
path <- "path_to_file.feather"
write_feather(df, path)
```
```Python
import(feather)
path = 'path_to_file.feather'
df = feather.read_dataframe(path)
```
___
## Error
```Python
In [4]: df = feather.read_dataframe(path)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-9cce2aa80994> in <module>()
----> 1 df = feather.read_dataframe(path)

/usr/local/lib/python2.7/site-packages/feather/api.pyc in read_dataframe(path, columns)
     53     data = {}
     54     for i in range(reader.num_columns):
---> 55         name, arr = reader.read_array(i)
     56         data[name] = arr
     57

/usr/local/lib/python2.7/site-packages/feather/ext.pyx in feather.ext.FeatherReader.read_array (feather/ext.cpp:3448)()
    186             values = timestamp_to_pandas(cp)
    187         else:
--> 188             raise NotImplementedError(cp.type())
    189
    190         return frombytes(cp.name()), values

NotImplementedError: 3
```
___
## Ideas
Not sure if it's a size/memory issue since the data frame is 17.7 million rows.  Seems to load fine in R as RDS or in Python as pickle/CSV.

**Comment by yitang** [comment]
i have the same issue here.

**Comment by wesm** [comment]
what's the total size of the written file?

**Comment by yitang** [comment]
I tried to read a file with 9.2M in size, and got this error.

**Comment by yitang** [comment]
This error only occurs in OSX. The linux desktop runs the same code with no problems.

**Comment by einheitActual** [comment]
my file is 2.6Gb
![screen shot 2016-05-22 at 1 23 25 pm](https://cloud.githubusercontent.com/assets/16613132/15455657/78948086-2020-11e6-80b9-e7995383c98a.png)

**Comment by wesm** [comment]
Got it, I think this will be solved by dealing with the > 2GB file size issue also described in #155. Sorry about this, I will look into it when I can.

**Comment by einheitActual** [comment]
No worries.  Thanks for looking into it.  I'm trying to standardize tools across our data management/data analysis/R+D teams, but in the meantime this will help with moving files around.  Once I get some more time I'd love to contribute...maybe an extension bundle for SPSS that can import/export feathers as well.

**Comment by wesm** [comment]
Cool, note: do not yet use Feather for long term data storage. The binary format may change in upcoming releases.

**Comment by wesm** [comment]
This should be fixed by #187. After we make a new release let us know if you still run into more problems

**Comment by wesm** [comment]
This should be working on master now via #187. Thanks

**Comment by matt-jay** [comment]
I got this same error when reading in a file of only 1.4 MB.

Full error message:

`
Traceback (most recent call last):

  File "<ipython-input-3-5257f2bb1505>", line 1, in <module>
    df = fe.read_dataframe('<path_and_filename>.feather')

  File "/Users/<username>/anaconda3/lib/python3.6/site-packages/feather/api.py", line 93, in read_dataframe
    arr = col.read()

  File "feather/ext.pyx", line 225, in feather.ext.Column.read (feather/ext.cpp:4296)

NotImplementedError: 3
`

**Comment by wesm** [comment]
Do you have an example of the file? When I make the Feather 0.4.0 release (soon) you may see if it's been magically fixed

**Comment by matt-jay** [comment]
It looks like 0.4 has fixed this. Thanks!
