### ISSUE TITLE
Question regarding 'memory specification' vs 'file format'.

### ISSUE THREAD

**Issue by jonathon-love** [wesm/feather#127]
hi,

i was just trying to get my head around arrow, and was a bit puzzled by these two statements, which appear to be contradictory.

> Feather uses the Apache Arrow columnar memory specification to represent binary data on disk.

and:

> Because Arrow does not provide a file format, Feather defines its own schemas and metadata for on-disk representation.

Apache arrow *is* a memory specification for representing binary data on disk, but at the same time does not provide a file format?

thanks

**Comment by wesm** [comment]
Let me try to lay out the distinction.

Let's take a super simple array data structure in C:

```C
typedef struct {
  /* the number of values in the array */
  int64_t length;

  /* the enum number indicating the data type of the array */
  type_t type;

  /* a contiguous block of allocated memory with size at least equal to length
   * sizeof(type) 
  */
  void* data;
} array_t;
```

This `array_t` is a **memory specification**. I haven't told you how to put it in a file yet.

Now suppose we have multiple arrays:

```C
array_t my_data[20];

/* populate my_data */
```

Now you want to write the data to a file. You have a memory representation for this data, but no file format. So now you have a bunch of decisions to make:

* how do you lay out the bytes contained in the `array_t` structs in the file?
* how to you encode the **metadata** (a description that allows code to reconstruct `my_data`)? 
* where do you put the metadata in the file?
* how do you verify that you have a valid file?

Hope this helps. Arrow provides the in-memory representation we are using to enable both Python and R (and other languages) to read and write Feather files in a language agnostic way.

**Comment by jonathon-love** [comment]
thanks, appreciate the clarification.

**Comment by wesm** [comment]
Thank you -- blogified for posterity: http://wesmckinney.com/blog/feather-and-apache-arrow/
