### ISSUE TITLE
feather-format now available on conda via conda-forge

### ISSUE THREAD

**Issue by jreback** [wesm/feather#134]
``conda install feather-format -c conda-forge``

for osx/linux-64

**Comment by billsanto** [comment]
This worked on OS X, but I did receive a warning during usage:

/Users/me/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used


From the installation:

Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/A/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.10.4               |           py27_0         3.0 MB
    numexpr-2.4.4              |      np110py27_0         103 KB
    scipy-0.16.0               |      np110py27_1        11.8 MB
    pandas-0.18.0              |      np110py27_0         5.8 MB
    feather-format-0.2.0       |           py27_0          90 KB
    ------------------------------------------------------------
                                           Total:        20.8 MB

The following NEW packages will be INSTALLED:

    feather-format: 0.2.0-py27_0      

The following packages will be UPDATED:

    numexpr:        2.4.3-np19py27_0   --> 2.4.4-np110py27_0 
    pandas:         0.18.0-np111py27_0 --> 0.18.0-np110py27_0
    scipy:          0.15.1-np19py27_0  --> 0.16.0-np110py27_1

The following packages will be DOWNGRADED:

    numpy:          1.11.0-py27_0      --> 1.10.4-py27_0     

Proceed ([y]/n)? y

**Comment by jreback** [comment]
is the message not clear? that's from pandas. you version of ``numexpr`` is a really buggy one. it won't be used. you can either downgrade ``numexpr`` after, or create a new env with numpy 1.11 which will use the latest of ``numexpr``. 

you can also ``conda install feather-format -c conda-forge --no-update-deps`` but you may need to upgrade ``conda`` before that (IIRC its a bit broken on some older versions)

**Comment by billsanto** [comment]
From what I understood of the message, the install of feather both upgraded numexpr from 2.4.3 to 2.4.4 and downgraded numpy to 1.10.4 from 1.11.0.  From your comment, I upgraded numpy to where it was, and now pandas is happy.  Thanks Jeff.

$ conda install numpy
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/me/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numexpr-2.5.1              |      np111py27_0         109 KB
    scipy-0.17.0               |      np111py27_0        12.9 MB
    ------------------------------------------------------------
                                           Total:        13.0 MB

The following packages will be UPDATED:

    numexpr: 2.4.4-np110py27_0  --> 2.5.1-np111py27_0 
    numpy:   1.10.4-py27_0      --> 1.11.0-py27_0     
    scipy:   0.16.0-np110py27_1 --> 0.17.0-np111py27_0

Proceed ([y]/n)?

**Comment by ogrisel** [comment]
BTW I have written a build script to generate manylinux1 wheels for all feather versions:

https://github.com/matthew-brett/manylinux-builds/blob/master/build_feathers.sh

All tests pass. It would be great to upload the resulting wheels to PyPI to help increase adoption.
There is also a script to generate manylinux1 wheels for all pandas versions in the same repo:

https://github.com/matthew-brett/manylinux-builds/blob/master/build_pandas.sh
