### ISSUE TITLE
[R] Solaris Problems

### ISSUE THREAD

**Issue by jeroenooms** [wesm/feather#136]
Note that I'm using R 3.1.2 in `C` locale because opencsw r-base has not been updated for a while... so there is a small chance the test failures are bugs in R which have been fixed.

1) The configure script doesn't work on solaris, but I assume you won't include that anyway? It looks like the configure script is intended to run at build time rather than install. 

2) This PR cleans up your Make and removes the GNU make dependency: https://github.com/wesm/feather/pull/135

3) On x86 we get 3 unit tests failures:

```
  testthat results ================================================================
  OK: 43 SKIPPED: 0 FAILED: 3
  1. Failure: always coerces to UTF-8 (@test-roundtrip-vector.R#51) 
  2. Failure: always coerces to UTF-8 (@test-roundtrip-vector.R#52) 
  3. Failure: doesn't lose undue precision (@test-roundtrip-vector.R#113) 
```

The first two failures seem to be losing their encoding attribute. This might be due to using the `C` locale.

```r
> expect_identical(Encoding(x), "latin1")
Error: Encoding(x) not identical to "latin1".
1/1 mismatches
x[1]: "unknown"
y[1]: "latin1"

> expect_identical(Encoding(y), "UTF-8")
Error: Encoding(y) not identical to "UTF-8".
1/1 mismatches
x[1]: "unknown"
y[1]: "UTF-8"
```

The third failure seems like a rounding problem:

```r
> expect_identical(x1, x2)
Error: `x1` not identical to `x2`.
Objects equal but not identical
> print(unclass(x1), digits = 20)
[1] 1002715200.0000000000 1002715200.0000009537 1002715200.0000020266
[4] 1002715200.0000029802
attr(,"tzone")
[1] "GMT"
> print(unclass(x2), digits = 20)
[1] 1002715200.0000000000 1002715200.0000000000 1002715200.0000020266
[4] 1002715200.0000020266
attr(,"tzone")
[1] "GMT"
```

4) On sparc (big endian) it installs but nothing works:

```r
> mtcars2 <- read_feather(feather_example("mtcars.feather"))
Error: Invalid: File is smaller than indicated metadata size

> library(testthat)
> test_package("feather")
class: Error: Invalid: File is smaller than indicated metadata size

DONE ===========================================================================
```

**Comment by wesm** [comment]
All the data stored in feather files is little endian. So to support big endian hardware, you'llneed to write some patches. I'll defer to @hadley and @krlmlr on the encoding issues

**Comment by hadley** [comment]
I think it's probably fine for us to say that we don't support big-endian platforms at this time.  I'll look into the other issues.

**Comment by hadley** [comment]
Hmmm, the round trip vector problem also happens on windows

**Comment by jeroenooms** [comment]
It might be an architecture issue then; solaris and windows are the only platforms that support 32bit.

**Comment by jeroenooms** [comment]
Re: sparc - R already has macro's which detect endianness and to SWAP bytes. So if we know which bytes need to be swapped, supporting big endian is not too difficult.

**Comment by jeroenooms** [comment]
The loss of precision problem on 32bit platforms is fixed with: https://github.com/wesm/feather/pull/141

**Comment by jeroenooms** [comment]
With https://github.com/wesm/feather/pull/141 and https://github.com/wesm/feather/pull/135 the problems are fixed for x86. I think the character encoding problem is due to some locale misconfiguration on my box or so. I don't think it will appear on CRAN.

I can look into the endian stuff but that might be pretty complex, not sure if it's worth it....

**Comment by hadley** [comment]
Yeah, I don't think we need to add support for big-endian systems.  Closing this because I think everything else is now covered. Thanks!
