### ISSUE TITLE
Write in chunks

### ISSUE THREAD

**Issue by wcbeard** [wesm/feather#137]
About the only nice thing I like about the csv format is the layout allows you to write large amounts of data to a file in chunks without storing it all in memory at once.

Could feather conceivably allow this, or is it fundamentally incompatible with the format?

**Comment by wesm** [comment]
Seems reasonably. We would need to evolve the format to allow multiple chunks (currently there is just 1 chunk).

**Comment by edwindj** [comment]
+1, I was about to ask the same question: Writing and reading(!) of chunks. 
This would broaden the use of feather a lot, for it allows one to work with large datasets.

**Comment by ScottPJones** [comment]
CSV format is row-major, feather is column-major, so wouldn't you be out of luck with feather if you had a row-major structure that you were adding new rows to?  I'm not sure how that would be handled with the arrow format or feather.  Any suggestions?

**Comment by wesm** [comment]
@ScottPJones I think what the user is suggesting is that we could have a feather file consisting of table chunks internally. For example: 10 chunks of 10 million rows. Logically the file contains 100,000,000 rows, but the issue with the current implementation is that all 100mm rows must be materialized in memory before the file can be created. It would be convenient if, given a known schema, you could build a feather table chunk by chunk (with the intermediate in-memory tables released from memory)

**Comment by ScottPJones** [comment]
Right, I guess my question is then, would each chunk have the columns laid out contiguously, in the feather format, for all of the rows in that chunk? Would the metadata be repeated in each chunk? If you wanted to process a particular column in a feather file, you would need to go chunk-by-chunk, processing 10 million values (stored contiguously), then seek to the next chunk, etc.?

**Comment by wesm** [comment]
No, there would be one metadata, but we would need auxiliary metadata to describe "row groups". See Parquet format for an example of this https://github.com/apache/parquet-format

**Comment by dermcnor** [comment]
I'll add a +1 for this functionality.  It could then be the go to format for block-wise/out-of-memory processing.

**Comment by monprin** [comment]
I'll also +1 this, we are dealing with a table that's around 320m rows and being able to run that on not just servers with excess memory would be incredibly helpful!

**Comment by wesm** [comment]
This is definitely high on my priority list, outside of the obvious critical bug fixes (like #155). I need to carve out a "Feather sprint" day.

**Comment by xiaodaigh** [comment]
+infinity on this feature
One of the reasons why SAS is still dominant in some industries and not overtaken by R or Python is because basically it's used as a data manipulation tool on disk. It can handle 50Gb files easily (but slowly) on a laptop using the on disk sas7bdat format. The "magic" of SAS is that it reads sas7bdat in chunks (pages) and then process it and write it out to disk, so not too much data is in memory at any one time, allowing it to churn through large amounts of data. But once feather supports chunks I predict SAS will die a slow and painful death, because I find that using R is way more productive than SAS.

**Comment by wesm** [comment]
I stand ready to implement this as soon as someone gets R bindings for the Arrow libraries off the ground.

**Comment by nzjrs** [comment]
Here seems as good of a place to ask as anywhere.... what is the modern way to do (small) chunked writing in the pydata/pyarrow stack that isn't 'write one csv line at a time' or is apache parquet `write_table` with `len(table) = 1` the best option

**Comment by wesm** [comment]
Want to discuss on dev@arrow.apache.org?

**Comment by Pooryamb** [comment]
Hi @wesm 

I have a Pandas dataframe, and I want to write it in chunks to the feather format. Could you please explain how can I do it? I could not find any examples on writing in chunks.

Thanks in advance,
