### ISSUE TITLE
[feature request] support for non UTF-8 encoded Unicode strings

### ISSUE THREAD

**Issue by ScottPJones** [wesm/feather#138]
In issue #74, it was brought up than only UTF-8 encoding for strings was supported by the feather format.
I believe that that can be rather limiting: https://github.com/wesm/feather/issues/74#issuecomment-217234474, since that doesn't work well with a number of languages that either use UTF-16, or support multiple internal representations (such as Python in 3.3 or later), Swift, or Julia.

Is there anything in the feather format that would make that difficult to support?

**Comment by wesm** [comment]
I suggest storing such strings as BINARY with some additional metadata indicating that the data is string and of a particular encoding

**Comment by ScottPJones** [comment]
OK, but, would that additional metadata be standardized and readers for different languages support the different Unicode encodings?  I'm not talking here about other character sets, simply a few very commonly used encodings of Unicode (UTF-16 and UTF-32, and strict subsets such as ASCII, ANSI Latin1, BMP only UTF-16).  Otherwise, if you are saving/restoring data between processes written in languages that both prefer UTF-16, for example, you incur a lot of overhead converting to/from UTF-8,
or you will have non-portable feather files.

**Comment by wesm** [comment]
Sure: make a proposal. Officially "string" will mean "utf8". If you want to store binary data encoding strings in some other day, that should be stored in the metadata for the binary column.

**Comment by wesm** [comment]
I support adding an optional "encoding" parameter to the metadata, which will be assumed to be UTF8 if not specified

**Comment by wesm** [comment]
Superseded by Feather V2 / use of Arrow IPC format
