### ISSUE TITLE
feather.read_dataframe does not read in columns in correct order

### ISSUE THREAD

**Issue by jakesherman** [wesm/feather#139]
Hello,

First off I love the package, especially because I frequently pass data between Python and R.

I found what may be a bug where a dataframe exported from R doesn't have the same column ordering when read into Python, instead it appears that the columns are sorted in alphabetical order. When exporting and then importing a dataframe in R, the column order is preserved. 

**To reproduce the issue:**

feather-test.R
```R
library("feather")
library("dplyr")

write_columns <- function(data, path) {
    
    # Writes the columns of a data.frame to text to use in conjunction with
    # feather for passing data in between Python and R
    data_frame(Names = names(data)) %>%
        write.table(path, row.names = FALSE, sep = '\t')
}

# Writing iris
iris <- as_data_frame(iris)
names(iris) <- gsub("\\.", "_", names(iris))
write_feather(iris, "iris.feather")

# Reading iris
iris_read <- read_feather("iris.feather")
print("Correct column order using read_feather")
print(identical(names(iris), names(iris_read)))

# Writing iris's column names
write_columns(iris, 'iris-columns.txt')
```

feather-test.py
```python
import numpy as np
import pandas as pd
import feather


def read_feather(myfile, columns):
    """
    Reads a feathered file into a Pandas DataFrame, using a .txt file of column 
    names to place columns in the correct order.
    """
    data = feather.read_dataframe(myfile)
    cols = pd.read_csv(columns, sep = '\t')
    return data.ix[:, list(cols['Names'])]


def correct_colorder(DataFrame):
    correct = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 
               'Species']
    return list(DataFrame) == correct


iris = feather.read_dataframe('iris.feather')

print 'Correct column order for feather.read_dataframe?', correct_colorder(iris)

iris2 = read_feather('iris.feather', 'iris-columns.txt')

print 'Correct column order for read_feather?', correct_colorder(iris2)
```

Run
```bash
Rscript feather-test.R
python feather-test.py
```

I am using Ubuntu 14.04 LTS with Python 2.7 and R 3.3.0. You can see my makeshift solution here where in R I use a `write_columns` function to write out the column names in order of a dataframe, and then use the `read_feather` function in Python to read in the dataframe in lieu of `feather.read_dataframe`.

Thanks!

**Comment by wesm** [comment]
I believe I fixed this here: https://github.com/wesm/feather/commit/06e69b0af92505e94ac785daf6c7f7d09236580c#diff-b0ec8005a8a066cd7b084e81ae2aa7b9R61

can you confirm which version of feather-python you are using?

**Comment by jakesherman** [comment]
I just upgraded to 0.2.0 and the problem is fixed, thank you!
