### ISSUE TITLE
ENH: Multi-dimensional arrays

### ISSUE THREAD

**Issue by MaximilianR** [wesm/feather#143]
Forgive me if this is a rookie question - I had a look on the Arrow docs but couldn't find anything.

How extensible could Arrow / Feather be to multidimensional arrays? Most of what's out there discusses serializing either an array or a table of arrays. Could something with ndim > 2 be serialized? Or would that be a format 'on top' of feather / arrow?

**Comment by wesm** [comment]
I'm open to having shape and order (Fortran or C) metadata, but since neither pandas.DataFrame nor R data.frame support multidimensional columns per se, I'm not sure it's in the scope of the project. It would be more advisable to use HDF5

**Comment by MaximilianR** [comment]
OK. Could be interesting to look at this as a backend to xarray. My C++ is very weak, so I'm not the one to spearhead this, but could potentially help with the python side. xarray also has the benefit that it already supports multiple backends (currently numpy & dask).

CC @shoyer

**Comment by shoyer** [comment]
To be a real xarray backend, xarray would need shape and order metadata per column, and also support for arbitrary user provided metadata fields.

**Comment by wesm** [comment]
Closing this. Arrow supports writes and zero-copy tensor reads from shared memory. See `arrow::ipc::ReadTensor` in http://arrow.apache.org/docs/cpp/ or https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_tensor.py

**Comment by shoyer** [comment]
Very nice, thanks @wesm !
