### ISSUE TITLE
Error trying to install via RStudio Server (Unix)

### ISSUE THREAD

**Issue by sco-lo-digital** [wesm/feather#148]
I'm trying to install Feather at work but ran into a problem trying to install via RStudio on Unix;

In file included from feather/api.h:22,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/buffer.h: In constructor ‘feather::MutableBuffer::MutableBuffer()’:
./feather/buffer.h:93: error: ‘nullptr’ was not declared in this scope
./feather/buffer.h: At global scope:
./feather/buffer.h:111: error: ‘constexpr’ does not name a type
./feather/buffer.h: In constructor ‘feather::BufferBuilder::BufferBuilder()’:
./feather/buffer.h:116: error: ‘nullptr’ was not declared in this scope
./feather/buffer.h: In member function ‘feather::Status feather::BufferBuilder::Append(const uint8_t*, int)’:
./feather/buffer.h:125: error: ‘MIN_BUFFER_CAPACITY’ was not declared in this scope
./feather/buffer.h: In member function ‘std::shared_ptr<feather::Buffer> feather::BufferBuilder::Finish()’:
./feather/buffer.h:141: error: ‘nullptr’ was not declared in this scope
./feather/buffer.h:146: error: ‘nullptr’ was not declared in this scope
In file included from feather/api.h:23,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/common.h: At global scope:
./feather/common.h:20: error: expected initializer before ‘const’
./feather/common.h:32: error: ‘constexpr’ does not name a type
./feather/common.h: In function ‘bool feather::util::get_bit(const uint8_t*, int)’:
./feather/common.h:35: error: ‘BITMASK’ was not declared in this scope
./feather/common.h: In function ‘bool feather::util::bit_not_set(const uint8_t*, int)’:
./feather/common.h:39: error: ‘BITMASK’ was not declared in this scope
./feather/common.h: In function ‘void feather::util::clear_bit(uint8_t*, int)’:
./feather/common.h:43: error: ‘BITMASK’ was not declared in this scope
./feather/common.h: In function ‘void feather::util::set_bit(uint8_t*, int)’:
./feather/common.h:47: error: ‘BITMASK’ was not declared in this scope
In file included from feather/api.h:24,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/io.h: In constructor ‘feather::LocalFileReader::LocalFileReader()’:
./feather/io.h:65: error: ‘nullptr’ was not declared in this scope
./feather/io.h: In constructor ‘feather::MemoryMapReader::MemoryMapReader()’:
./feather/io.h:91: error: ‘nullptr’ was not declared in this scope
./feather/io.h: In constructor ‘feather::FileOutputStream::FileOutputStream()’:
./feather/io.h:178: error: ‘nullptr’ was not declared in this scope
In file included from feather/api.h:25,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/metadata.h: In constructor ‘feather::metadata::Table::Table()’:
./feather/metadata.h:150: error: ‘nullptr’ was not declared in this scope
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘feather’
* removing ‘/home/Scott.Jacobs/R/x86_64-redhat-linux-gnu-library/3.2/feather’
Error: Command failed (1)

**Comment by wesm** [comment]
Feather requires a C++11-capable gcc, at least gcc 4.8 (4.9 or higher recommended). On RedHat you can install the devtoolset to get the newer gcc, but I don't know the precise details
