### ISSUE TITLE
Error trying to install via pip on Windows (10) using anaconda 2.7

### ISSUE THREAD

**Issue by pyeguy** [wesm/feather#151]
I love the idea of this package and thank you to for creating it. 
but....

 i'm having a bear of a time getting it installed. Anaconda sometimes doesn't play nice, but even conda recipies for 64bit windows fail.  

Attached are text files of the pip failed installs using Microsoft Visual C++ 9.0 (reccommended for Python 2.7) and MinGW (latest GCC as near as I can tell)

not to rub salt in the wound but it seems like there are a lot of issues in regards to installation, if feather is supposed to be a fast, convenient way to share dataframes it seems like the install needs to be a bit general and painless to encourage adoption. 

Thanks for any help the (much) more informed user base can provide. looking forward to ruffling some feathers... 

[feather_install_log_VisualCpp.txt](https://github.com/wesm/feather/files/269187/feather_install_log_VisualCpp.txt)
[feather_install_log_MinGW.txt](https://github.com/wesm/feather/files/269188/feather_install_log_MinGW.txt)

**Comment by wesm** [comment]
Ouch!

Per https://github.com/conda-forge/feather-format-feedstock/issues/1, I believe regrettably that Feather, Windows, and Python 2.7 may not be a viable combo (@msarahan, can you provide some more color on this?) unless a kind soul backports the C++ code to C++03 (we're using C++11). 

Python 3.5 should work for you, but you'll need to use the git master version until I post a new PyPI release with recent Windows fixes (https://github.com/wesm/feather/commit/e27a58e3fbab9b32aec4a1ed4b5779cd8779dbeb).

**Comment by msarahan** [comment]
This article sums up the reasons why well: http://siomsystems.com/mixing-visual-studio-versions/ - you can't have C++11 without a newer compiler, and you can't have a newer compiler, because you'd be mixing runtimes.

Your only options are to use a non-standard python2.7  interpreter - either MSYS2 (and use GCC for compiling feather), or create a whole new Python2.7 stack that isn't compatible with many other Python 2.7 packages out there.

**Comment by pyeguy** [comment]
right on. thanks for the quick replies. you guys rock. python on windows often does not...

I love pandas and I love the anaconda stack but it looks like feather won't be joining the party in my current dev environment. Maybe the 2.7 --> 3 gap has gotten wide enough that I should make the leap. I think this is the first time I'd be opting for 3 because it actually _supports_ a package I want to use...

Maybe when windows rolls out the subsystem for linux we can all be one happy family again.

keep up the awesome work!
