### ISSUE TITLE
Install Failure on Windows 10 (R Package from CRAN)

### ISSUE THREAD

**Issue by blueskyprogrammer** [wesm/feather#156]
install.packages("feather")
Installing package into ‘C:/Users/BSP/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘feather’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘feather’

trying URL 'https://cran.rstudio.com/src/contrib/feather_0.0.1.tar.gz'
Content type 'application/x-gzip' length 49068 bytes (47 KB)
downloaded 47 KB

Loading required package: datasets
Loading required package: utils
Loading required package: pryr
* installing *source* package 'feather' ...
** package 'feather' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather-read.cpp -o feather-read.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather-types.cpp -o feather-types.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather-write.cpp -o feather-write.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather/buffer.cc -o feather/buffer.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather/feather-c.cc -o feather/feather-c.o
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather/io.cc -o feather/io.o
feather/io.cc:18:0: warning: "NOMINMAX" redefined [enabled by default]
c:\rbuildtools\3.3\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../include/c++/4.6.3/i686-w64-mingw32/bits/os_defines.h:46:0: note: this is the location of the previous definition
g++ -m32 -std=c++0x -I"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/include" -DNDEBUG -I.   -I"C:/Users/BSP/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c feather/metadata.cc -o feather/metadata.o
feather/metadata.cc:29:7: error: expected nested-name-specifier before 'FBString'
feather/metadata.cc:29:7: error: 'FBString' has not been declared
feather/metadata.cc:29:16: error: expected ';' before '=' token
feather/metadata.cc:29:16: error: expected unqualified-id before '=' token
feather/metadata.cc:32:7: error: expected nested-name-specifier before 'ColumnVector'
feather/metadata.cc:32:7: error: 'ColumnVector' has not been declared
feather/metadata.cc:32:20: error: expected ';' before '=' token
feather/metadata.cc:32:20: error: expected unqualified-id before '=' token
feather/metadata.cc:178:3: error: 'ColumnVector' does not name a type
feather/metadata.cc: In member function 'feather::Status feather::metadata::TableBuilder::Impl::Finish()':
feather/metadata.cc:146:5: error: 'FBString' was not declared in this scope
feather/metadata.cc:146:14: error: expected ';' before 'desc'
feather/metadata.cc:148:7: error: 'desc' was not declared in this scope
feather/metadata.cc:154:9: error: 'desc' was not declared in this scope
feather/metadata.cc:156:27: error: 'columns_' was not declared in this scope
feather/metadata.cc:157:34: error: unable to deduce 'auto' from '<expression error>'
feather/metadata.cc: In member function 'void feather::metadata::TableBuilder::Impl::add_column(const flatbuffers::Offset<feather::fbs::Column>&)':
feather/metadata.cc:173:5: error: 'columns_' was not declared in this scope
feather/metadata.cc: In constructor 'feather::metadata::TableBuilder::TableBuilder()':
feather/metadata.cc:190:5: error: type 'feather::metadata::TableBuilder' is not a direct base of 'feather::metadata::TableBuilder'
make: *** [feather/metadata.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/etc/i386/Makeconf" -f "C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="feather.dll" OBJECTS="RcppExports.o feather-read.o feather-types.o feather-write.o"' had status 2
ERROR: compilation failed for package 'feather'
* removing 'C:/Users/BSP/Documents/R/win-library/3.2/feather'
Warning in install.packages :
  running command '"C:/Users/FREAKA~1/DOCUME~1/R/R-32~1.5/bin/x64/R" CMD INSTALL -l "C:\Users\BSP\Documents\R\win-library\3.2" C:\Users\FREAKA~1\AppData\Local\Temp\Rtmp8QDO0Z/downloaded_packages/feather_0.0.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘feather’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\BSP\AppData\Local\Temp\Rtmp8QDO0Z\downloaded_packages’

**Comment by hadley** [comment]
Unfortunately feather is only supported in R >3.3.0 on windows (that's the first version to gain the C++ support that we need)

**Comment by blueskyprogrammer** [comment]
Thanks, all is well with the upgrade install.
