### ISSUE TITLE
read first x rows of feather file

### ISSUE THREAD

**Issue by Bart6114** [wesm/feather#158]
Just wondering if partial loading is on the roadmap.

Let's say I have a _large_ dataset which I don't completely want to load into memory but I do want to have a peek at it. Will it every be possible to load the first x rows?

**Comment by hadley** [comment]
It's already possible on the R side:

```R
f <- feather("my-file.feather")
feather[1:10, ]
```

**Comment by wesm** [comment]
Yes, definitely would like to also have this in the Python interface. This would be an accessible patch for someone to work on

**Comment by dpastoor** [comment]
@hadley 

I assume in this example you mean

```
f[1:10,]
```

What is going on, is it some sort of streaming? The reason I ask, is it is completely crashing my R session (windows w/ R 3.3) every time I try, however it is not competely reproducible based on dataset size alone (see mtcars example below that works).

I am working off an ~700 MB feather file, that loads completely fine via read_feather() but crashes out after ~1-2 minutes. Monitoring memory of the rsession shows something going on as the memory creeps up ~20MB during that time, with 100% CPU utilization of the process, before crashing. Still have plenty of memory available on the system.

Yet this works:

```
library(feather)
library(dplyr)
write_feather(lapply(1:500000, function(x) {
  mtcars %>% mutate(REP = x)
}) %>% bind_rows, "mtcars500000.feather") #approx 1 gig file

mtcarsf <- feather("mtcars500000.feather")

mtcarsf[1:10,] #works fine
```


I am trying to troubleshoot what might be the issue.

**Comment by dpastoor** [comment]
Ok, some very particular behavior going on.

1) If the object has been accessed via read_feather, then is further accessed via feather it WORKS

```
labs2 <- read_feather("C:\\Users\\Devin.Pastoor\\Documents\\Repos\\.cache\\d8733fe2f24ec7a_LB.feather")
## access again but this time as just a feather object
labs3 <- feather::feather("C:\\Users\\Devin.Pastoor\\Documents\\Repos\\.cache\\d8733fe2f24ec7a_LB.feather")
labs3[1:10, ] # works fine
```

2) If I then restart the R session, and then just go immediately to reading, IT CRASHES
```
## labs2 <- read_feather("C:\\Users\\Devin.Pastoor\\Documents\\Repos\\.cache\\d8733fe2f24ec7a_LB.feather")
## don't read labs2
labs3 <- feather::feather("C:\\Users\\Devin.Pastoor\\Documents\\Repos\\.cache\\d8733fe2f24ec7a_LB.feather")
labs3[1:10, ] # works fine
```

3) furthermore, the feather object is corrupted, making it unreadable, so now trying to run

```
#worked previously
labs2 <- read_feather("C:\\Users\\Devin.Pastoor\\Documents\\Repos\\.cache\\d8733fe2f24ec7a_LB.feather")
```

likewise crashes, forcing the file to be deleted and re-created.



Might this be due to large numbers of factor variables with lots of levels:

```
str(labs) # -->

'data.frame':	5684911 obs. of  28 variables:
 $ STUDYID : Factor w/ 1 level "1160-0026": 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "Study Identifier"
 $ DOMAIN  : Factor w/ 1 level "LB": 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "Domain Abbreviation"
 $ USUBJID : Factor w/ 18112 levels "1160-0026-00001001",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "Unique Subject Identifier"
 $ LBSEQ   :Classes 'labelled', 'integer'  atomic [1:5684911] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..- attr(*, "label")= chr "Sequence Number"
 $ LBGRPID : Factor w/ 6396 levels "105-1","105-10",..: NA NA NA NA NA NA 102 1 116 12 ...
  ..- attr(*, "label")= chr "Group ID"
 $ LBREFID : Factor w/ 228446 levels "*","05607893",..: 2946 4479 4478 30513 87859 87856 2946 2946 4481 4481 ...
  ..- attr(*, "label")= chr "Specimen ID"
 $ LBSPID  : Factor w/ 17 levels "1","10","11",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "label")= chr "Sponsor-Defined Identifier"
 $ LBTESTCD: Factor w/ 141 levels "A1AT","ACANTH",..: 3 3 3 3 3 3 5 5 5 5 ...
  ..- attr(*, "label")= chr "LAB Test or Examination Short Name"
 $ LBTEST  : Factor w/ 141 levels "ACANTHOCYTES (QUAL)",..: 4 4 4 4 4 4 5 5 5 5 ...
  ..- attr(*, "label")= chr "LAB Test or Examination Name"
 $ LBCAT   : Factor w/ 13 levels "CHEMISTRY","CHEMISTRY LABORATORY RESULTS",..: 1 1 1 1 1 1 7 7 7 7 ...
  ..- attr(*, "label")= chr "Category for Lab Test"
 $ LBSCAT  : Factor w/ 15 levels "ENHANCED HEP FUNCTION",..: 9 12 13 14 10 15 NA NA NA NA ...
  ..- attr(*, "label")= chr "Subcategory for Lab Test"
 $ LBORRES : Factor w/ 4186 levels "-9","+-","< 80",..: 2568 2568 2255 2568 2590 2614 3325 3325 3561 3561 ...
  ..- attr(*, "label")= chr "Result or Finding in Original Units"
 $ LBORRESU: Factor w/ 33 levels "%","10^12/L",..: 12 12 12 12 12 12 29 29 29 29 ...
  ..- attr(*, "label")= chr "Original Units"
 $ LBORNRLO: Factor w/ 1158 levels "< 80","<1000",..: 583 583 583 583 583 583 NA 724 NA 724 ...
  ..- attr(*, "label")= chr "Reference Range Lower Limit in Orig Unit"
 $ LBORNRHI: Factor w/ 1548 levels "0","0.0","0.00",..: 1026 1026 1026 1026 1026 1026 NA 394 NA 394 ...
  ..- attr(*, "label")= chr "Reference Range Upper Limit in Orig Unit"
 $ LBSTRESC: Factor w/ 6391 levels ".","0","0.005847",..: 4127 4127 3544 4127 4143 4157 5390 5390 5683 5683 ...
  ..- attr(*, "label")= chr "Character Result/Finding in Std Format"
 $ LBSTRESN:Classes 'labelled', 'numeric'  atomic [1:5684911] 4.4 4.4 3.6 4.4 4.5 4.6 68 68 75 75 ...
  .. ..- attr(*, "label")= chr "Numeric Result/Finding in Standard Units"
 $ LBSTRESU: Factor w/ 10 levels "%","10^12/L",..: 5 5 5 5 5 5 10 10 10 10 ...
  ..- attr(*, "label")= chr "Standard Units"
 $ LBSTNRLO:Classes 'labelled', 'numeric'  atomic [1:5684911] 3.2 3.2 3.2 3.2 3.2 3.2 NA 45 NA 45 ...
  .. ..- attr(*, "label")= chr "Reference Range Lower Limit-Std Units"
 $ LBSTNRHI:Classes 'labelled', 'numeric'  atomic [1:5684911] 4.6 4.6 4.6 4.6 4.6 4.6 NA 145 NA 145 ...
  .. ..- attr(*, "label")= chr "Reference Range Upper Limit-Std Units"
 $ LBNRIND : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "label")= chr "Reference Range Indicator"
 $ LBSTAT  : Factor w/ 1 level "NOT DONE": NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "label")= chr "Lab Status"
 $ LBNAM   : Factor w/ 2 levels "CENTRAL LAB",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "Vendor Name"
 $ LBBLFL  : Factor w/ 1 level "Y": 1 NA NA NA NA NA 1 1 NA NA ...
  ..- attr(*, "label")= chr "Baseline Flag"
 $ VISIT   : Factor w/ 138 levels "1 MONTH FOLLOW-UP",..: 29 18 23 4 45 19 29 29 1 1 ...
  ..- attr(*, "label")= chr "Visit Name"
 $ VISITNUM:Classes 'labelled', 'numeric'  atomic [1:5684911] 1 5 6 8 11 ...
  .. ..- attr(*, "label")= chr "Visit Number"
 $ LBDTC   : Factor w/ 9094 levels "2005-05-23","2005-05-25",..: 270 564 951 1790 6947 8985 270 270 374 374 ...
  ..- attr(*, "label")= chr "Date/Time of Specimen Collection"
 $ LBDY    :Classes 'labelled', 'integer'  atomic [1:5684911] -5 86 179 365 803 988 -5 -5 31 31 ...
  .. ..- attr(*, "label")= chr "Study Day of Specimen Collection"
 - attr(*, "label")= chr "Laboratory Test Results - LB"
 - attr(*, "SAStype")= chr " "
```

**Comment by kendonB** [comment]
For those that land here from Google, I'm unable to see any speed benefit from subsetting feather store objects by rows: https://github.com/wesm/feather/issues/319

See also: https://github.com/wesm/feather/issues/306

**Comment by wesm** [comment]
We could implement this easily in Feather V2 coming in `arrow` 0.17.0  Please feel free to open a JIRA issue in Apache Arrow

**Comment by jyk4100** [comment]
Sorry to circle back on a old post - Is reading first n rows from a feather file available for the python interface? I couldn't find it on [read_feather](https://arrow.apache.org/docs/python/generated/pyarrow.feather.read_feather.html) or [read_table](https://arrow.apache.org/docs/python/generated/pyarrow.feather.read_table.html)

**Comment by wesm** [comment]
It isn't, would you like to open a Jira issue? 

https://arrow.apache.org/docs/developers/guide/communication.html#jira

**Comment by jyk4100** [comment]
https://issues.apache.org/jira/browse/ARROW-16698

**Comment by jyk4100** [comment]
Is it possible to read subset of columns from a csv file into arrow table?
it appears it is possible on R [read_delim_arrow](https://ursalabs.org/arrow-r-nightly/reference/read_delim_arrow.html) but  not on Python [pyarrow.csv.ReadOptions](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions) ?

**Comment by wesm** [comment]
If there doesn't seem to be a way to do it in Python please open an issue

**Comment by nealrichardson** [comment]
For what it's worth, the csv reading in R filters the columns after reading into Arrow but before pulling into an R data.frame. There's a TODO comment suggesting that it could be pushed down into the converter: https://github.com/apache/arrow/blob/master/r/R/csv.R#L210-L214
