### ISSUE TITLE
Standard Definition of Type Storage?

### ISSUE THREAD

**Issue by quinnj** [wesm/feather#164]
Are there standard definitions of how the Date, Timestamp, and Time columns are being stored? It seems like they are probably a unix timestamp (i.e. seconds/milliseconds since 1970), but I can't find anything official.

I'm trying to wrap my head around any necessary conversion methods going from Arrow/Feather format to more common Julia structures (`Date`, `DateTime`).

**Comment by wesm** [comment]
They're UNIX timestamps -- we should definitely add some documentation about this

**Comment by quinnj** [comment]
I can do a PR; what about Time, is it the # of time units since midnight?

**Comment by wesm** [comment]
Yep

**Comment by wesm** [comment]
In Feather V2 we now use the Arrow IPC format and metadata and this is all documented there
