### ISSUE TITLE
[R] Make clear that feather is little-endian

### ISSUE THREAD

**Issue by hadley** [wesm/feather#167]
BDR says "You check it in a configure script, and it is a SystemRequirements."

@jeroenooms can you translate that into something concrete?

**Comment by jeroenooms** [comment]
Sure

**Comment by jeroenooms** [comment]
This fixes it: https://github.com/wesm/feather/pull/168

**Comment by wesm** [comment]
merged in https://github.com/wesm/feather/commit/b4cc44de55aa0b72d7e216ff7f777a8155495bad
