### ISSUE TITLE
Error while installing 'feather'

### ISSUE THREAD

**Issue by samrus98** [wesm/feather#169]
**Hello, I am trying to install package 'rio' and get the following error while installing dependency 'feather'**

> installing source package 'feather' ... ** package 'feather' successfully unpacked and MD5 sums checked ** libs
> *** arch - i386
> Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-devel/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-devel/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="feather.dll" OBJECTS="RcppExports.o feather-read.o feather-types.o feather-write.o"' had status 127
> ERROR: compilation failed for package 'feather'
> 
> removing 'C:/Users/User_0126_05/Documents/R/win-library/3.4/feather' Warning in install.packages : running command '"C:/PROGRA~1/R/R-devel/bin/x64/R" CMD INSTALL -l "C:\Users\User_0126_05\Documents\R\win-library\3.4" C:\Users\USER_0~1\AppData\Local\Temp\RtmpmSxgP5/downloaded_packages/feather_0.0.1.tar.gz' had status 1 Warning in install.packages : installation of package ‘feather’ had non-zero exit status ERROR: dependency 'feather' is not available for package 'rio'
> removing 'C:/Users/User_0126_05/Documents/R/win-library/3.4/rio' Warning in install.packages : running command '"C:/PROGRA~1/R/R-devel/bin/x64/R" CMD INSTALL -l "C:\Users\User_0126_05\Documents\R\win-library\3.4" C:\Users\USER_0~1\AppData\Local\Temp\RtmpmSxgP5/downloaded_packages/rio_0.4.6.tar.gz' had status 1 Warning in install.packages : installation of package ‘rio’ had non-zero exit status

**When I try to install 'feather' separately, I still get the following error:**

installing source package 'feather' ... ** package 'feather' successfully unpacked and MD5 sums checked ** libs
*** arch - i386
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-devel/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-devel/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="feather.dll" OBJECTS="RcppExports.o feather-read.o feather-types.o feather-write.o"' had status 127
ERROR: compilation failed for package 'feather'

removing 'C:/Users/User_0126_05/Documents/R/win-library/3.4/feather' Warning in install.packages : running command '"C:/PROGRA~1/R/R-devel/bin/x64/R" CMD INSTALL -l "C:\Users\User_0126_05\Documents\R\win-library\3.4" C:\Users\USER_0~1\AppData\Local\Temp\RtmpmSxgP5/downloaded_packages/feather_0.0.1.tar.gz' had status 1 Warning in install.packages : installation of package ‘feather’ had non-zero exit status

**Can anybody help?**

-Sam

**Comment by hadley** [comment]
Is there a reason you're not installing from CRAN?

**Comment by samrus98** [comment]
Hadley,

I am trying to install from Cran using install.packages. I guess it is confusing that I posted here. Should I be posting this question on Stackoverflow instead?

-Sam

**Comment by jeroenooms** [comment]
Why are you using r-devel 3.4? Try using R 3.3 instead.

**Comment by MySchizoBuddy** [comment]
No luck even installing from CRAN
`Warning in install.packages :
  unable to move temporary installation ‘C:\Users\Ziyad\Documents\R\win-library\3.3\file2fa0282827eb\feather’ to ‘C:\Users\Ziyad\Documents\R\win-library\3.3\feather’`
