### ISSUE TITLE
Investigate symlink issues for rstudio users

### ISSUE THREAD

**Issue by wesm** [wesm/feather#173]
per @krlmlr comment

https://github.com/wesm/feather/commit/b4cc44de55aa0b72d7e216ff7f777a8155495bad#commitcomment-17660819

**Comment by krlmlr** [comment]
@hadley: Symlinked dirs are not searched in RStudio 0.99.1130 (with Ctrl+Shift+F). Do you know if this will be fixed any time soon, or perhaps has been fixed already?

**Comment by krlmlr** [comment]
Even worse: Symlinks are converted to plain-text files on Windows. May I suggest reverting to the rsync-cp dance from the commit linked above?

**Comment by wesm** [comment]
Closing now that we have Feather V2 coming in Arrow 0.17.0. If these issues come up with the `arrow` package please open an issue in Apache Arrow

**Comment by dxf1david** [comment]
Wes - it's good to know there's a new version of feather coming, but I'm
fairly sure that you meant to send this to someone other than me.  I'm a
biostatistician at CDC and an R user.  AFAIK, I've never used Arrow; I'm
not even sure what it is.

david freedman, atlanta

**Comment by wesm** [comment]
@dxf1david are you "watching" this repository on GitHub? The relationship between Feather and Arrow is explained in this README of this repository.

**Comment by dxf1david** [comment]
how embarrassing - yes, I am watching the thread

thanks for all the work you've done on  feather - good to know there's a
new version coming

david
