### ISSUE TITLE
Set up C++ microbenchmarking tools using google/benchmark

### ISSUE THREAD

**Issue by wesm** [wesm/feather#18]
Enable us to do micro-optimizations on various code paths (and explore parallelization / pipelining)

**Comment by chadbrewbaker** [comment]
I would be happy to help with this. Perhaps a public S3 bucket with test data sets and a few hello world codes that exercise some of the critical data pipelines?

I have C++ running on AWS Lambda, https://github.com/chadbrewbaker/introToAWSLambda so scrounging up boxes to benchmark on isn't an issue.

**Comment by wesm** [comment]
Feather reads are zero-copy in https://github.com/apache/arrow/tree/master/cpp/src/arrow/ipc; so the benchmarks will be specific to the R or Python conversion to DataFrame
