### ISSUE TITLE
Add an "epoch" field to TimestampMetadata/DateMetadata?

### ISSUE THREAD

**Issue by quinnj** [wesm/feather#185]
Some systems use epoch's different from 1970-01-01, such as 0000-01-01 (Rata Die epoch), or Julian epoch (-4713-11-24T12:00:00).

I wonder if it would make sense to add an `epoch` string field to the TimestampMetadata and DateMetadata types in order to capture the epoch of the time values in those columns.

I realize there's always a tradeoff between allowing more functionality and keeping things simple, but it would, for example, greatly simplify the Julia DateTime conversions (which are based on the Rata Die epoch due to the simplicity of different date calculations it allows).

**Comment by hadley** [comment]
This seems of limited utility to me.

**Comment by wesm** [comment]
closing as won't fix
