### ISSUE TITLE
feather drops data without warning if column data is of mixed type

### ISSUE THREAD

**Issue by sdelatorre** [wesm/feather#189]
I noticed odd behavior when writing/reading a dataframe that contained columns with data of mixed-types. Instead of throwing an error or showing a warning, feather silently drops the second data type it encounters.

Admittedly, the reason the columns had mixed data types in the first place is because I missed a column-type conversion before concatenating the dataframes (yes, I need better unit tests), so I'm not requesting a feature making that possible. Instead, it would be helpful if feather stopped processing the file or at least printed a warning instead of silently dropping data. Here's a sample script to demonstrate the behavior:

```
# feather version: 0.2.0
# python version: Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
import feather
import pandas

rec_1 = {'a': '1', 'b': '2'}
rec_2 = {'a': 2, 'b': 2}

df1 = pd.DataFrame([rec_1, rec_2])
df1 = pd.DataFrame([rec_1, rec_2])
combined = pd.concat([df1, df2])
combined
```

outputs:

```
   a  b
0  1  2
1  2  2
0  1  2
1  2  2
```

Now, if I write/read the dataframe, I see missing data:

```
feather.write_dataframe(combined, 'out.feather')
feather.read_dataframe('out.feather')
```

output:

```
      a     b
0     1     2
1  None  None
2     1     2
3  None  None
```

Thanks!

**Comment by wesm** [comment]
This is now handled by `pyarrow`, which will raise on mixed type data
