### ISSUE TITLE
feather ignores the dataframe index?

### ISSUE THREAD

**Issue by dhirschfeld** [wesm/feather#191]
![image](https://cloud.githubusercontent.com/assets/881019/16027786/2d15aae6-321c-11e6-9260-71acf7499813.png)

**Comment by wesm** [comment]
https://github.com/wesm/feather/tree/master/python#limitations

**Comment by dhirschfeld** [comment]
Sorry, I probably should have looked a bit harder before opening an issue  - thanks @wesm for pointing it out.

~~Is this a fundamental limitation? Would it not be possible to unconditionally do a `reset_index` on the dataframe and store a list of index columns in the metadata?~~ ...I see @jreback has already requested this in #74 so I'll close this issue as a dup.
