### ISSUE TITLE
first column overwritten by second in Python-to-R data frame

### ISSUE THREAD

**Issue by MaryLvV** [wesm/feather#196]
I am working on a MacBookPro running OS X El Capitan (10.11.4).  I am using feather 0.2.0 in python 3.5 to create data frames from historic tweets.  I am collecting a list of tweets and them mapping them to a data frame with code that looks like this:

```{python}
import glob
import pandas as pd
import json
import feather

def get_body(tweet):
    body = tweet.get('body')
    if body == None: return 'NA'
    return body
    
def get_datetime (tweet):
    datetime = tweet.get('postedTime')
    if datetime == None: return 'NA'
    return datetime
    
def get_location(tweet):
    actor = tweet.get('actor')
    if actor == None: return 'NA'
    
    location = actor.get('location')
    if location == None: return 'NA'
    
    display_name = location.get('displayName')
    if display_name == None: return 'NA'
    
    return display_name

input_folder = 'SandyHook/SH8/*.json'
output_file = './tweets_df/sh8.feather'
tweets_data =[]
file_count = 0
for file in glob.iglob(input_folder, recursive=True):
        tweets_file = open(file, "r")
        file_count = file_count + 1
        if file_count % 50 == 0:
            print('file count is ' + str(file_count))
        for line in tweets_file:
            try:
                if 'body' in line:
                    tweet = json.loads(line)
                    tweets_data.append(tweet)
            except:
                continue
                
df = pd.DataFrame()
df['tweet'] = [get_body(tweet) for tweet in tweets_data]
df['datetime'] = [get_datetime(tweet) for tweet in tweets_data]
df ['location'] = [get_location(tweet) for tweet in tweets_data]
feather.write_dataframe(df, output_file)
```
When I read some of the feather data frames into R, the first column gets overwritten with the second column (inconsistently) -- or a couple of times the last column gets transformed to TRUE/FALSE.  If I read the same feather dataset back into python, it looks fine.

I thought there might be something in the data causing this, so I recreated one of the squirrelly data frames in two halves.  Both halves were fine when I read them into R! 

In R, I am using version 3.3.1 with feather 0.0.1.9.  I am simply reading the file in with  
```{r}
sh8 <- read_feather("tweets_df/sh8.feather")
```
Below, sh4 is a data frame that did not read in correctly.  I split the source files and recreated two subsets (sh4a and sh4b) in python which read into R just fine.

<img width="782" alt="screen shot 2016-06-26 at 4 41 44 pm" src="https://cloud.githubusercontent.com/assets/8145655/16895094/46786002-4b38-11e6-8d9c-eea9525dabf7.png">

Here is a warning I get when viewing the bad data frame:
<img width="909" alt="screen shot 2016-06-26 at 4 45 56 pm" src="https://cloud.githubusercontent.com/assets/8145655/16895106/8c542a20-4b38-11e6-9c0a-d3cc70305d56.png">

I am having trouble pinpointing the cause, especially since when I split the raw data both halves work fine.

**Comment by hadley** [comment]
Can you please try the latest dev version?  It may be related to some gc bugs that we fixed.

**Comment by MaryLvV** [comment]
Looks like that fixed my issue.  Thanks!
