### ISSUE TITLE
Error reading colum names. UTF-8

### ISSUE THREAD

**Issue by skanskan** [wesm/feather#198]
Hello.

It seems that read_feather doesn't read well some columnames.
Other similar packages let you enable the UTF-8 option,  I think it's related with that.
Could you please add that option too, please?

For example a column name  "año"  appears as "aÃ±o"

**Comment by wesm** [comment]
Marking this as an R bug (?), I just verified that UTF-8 is being minded at least on Python 3.5

```python
In [1]: import feather

In [2]: import pandas as pd

In [3]: df = pd.DataFrame({'año': [1,2,3,4]})

In [4]: df
Out[4]: 
   año
0    1
1    2
2    3
3    4

In [5]: feather.write_dataframe(df, 'foo.feather')

In [6]: feather.read_dataframe('foo.feather')
Out[6]: 
   año
0    1
1    2
2    3
3    4
```
