### ISSUE TITLE
Index lost during pandas-feather-pandas roundtrip

### ISSUE THREAD

**Issue by aleyan** [wesm/feather#200]
When persisting a pandas DataFrame to feather, the row index seems to get lost. When pulling the frame out again, the index is replaced with a RangeIndex. The column index remains intact.

This [example notebook](https://gist.github.com/aleyan/76b230f3f1eca4de500107f6e6e53caf) illustrates the issue.

Not sure if this is a design decision or a bug or something else. My use case for feather is to roundtrip data through the filesystem with greater confidence that it won't get mangled like in CSVs. For now my work around is to reset_index() before saving and then do set_index() after loading.

**Comment by wesm** [comment]
Currently, serializing pandas row indexes is an unsupported feature (see https://github.com/wesm/feather/tree/master/python#limitations).

I am in favor of adding some column metadata that enables non-trivial indexes to be reconstructed automatically, and at least this data can be read by R, perhaps with some manual scrutiny. We'd need to make some arbitrary decisions, like what name to give the "index column".

**Comment by wesm** [comment]
I think this can be easily handled now in the Arrow-based feather implementation. I'll leave this open and make sure there's a corresponding issue in Apache Arrow for this

**Comment by ybagdasa** [comment]
Just encountered the error with the conda-forge / packages / feather-format 0.4.1 installation. Also using the reset_index() workaround.

**Comment by mikecoder5** [comment]
@wesm are indexes fully supported? Some (or all) indexes are converted to a `RangeIndex` after a serialization/deserialization round trip. I came across this in pyarrow 3.0.0 and 6.0.1 for both a `MultiIndex` and an empty dataframe (`Dataframe.index`).

**Comment by wesm** [comment]
can you open an issue upstream in Apache Arrow?

**Comment by mikecoder5** [comment]
@wesm done, https://issues.apache.org/jira/browse/ARROW-15018

**Comment by mikecoder5** [comment]
@wesm Any thoughts on the issue? Is this something we can get a quick fix for or is it a larger task? If we can support it in Apache, I can move forward with [propagating the support into Pandas](https://github.com/pandas-dev/pandas/issues/28208#issuecomment-984011872).

**Comment by wesm** [comment]
@mikecoder5 you should be able to comment on Jira now
