### ISSUE TITLE
read_dataframe call is not using the "columns" parameter 

### ISSUE THREAD

**Issue by benitocm** [wesm/feather#202]
It seems that the read_dataframe call is not using the "columns" parameter to choose which columsns from the file to read. For small files, i think is not a problem but in the case of large files it would be very helpful that the call just read the needed columns to optimize, mainly, the memory used to load the dataframe.

**Comment by wesm** [comment]
Would gladly welcome some PRs around improving the Python API

**Comment by wesm** [comment]
Closed in #218
