### ISSUE TITLE
"Warning: Coercing int64 to double"

### ISSUE THREAD

**Issue by RoyalTS** [wesm/feather#206]
This may not be so much an issue as a question: Why does feather coerce int64 to double upon `read_feather()`? Why not convert it to integer?

**Comment by hadley** [comment]
Because it would lose more information.

**Comment by RoyalTS** [comment]
Are there any feather column types that get cast to integer upon read into R?

**Comment by wesm** [comment]
Anything smaller than int64_t. It might be possible to have R only cast to double when it encounters an out of range value (> 2^53)

**Comment by RoyalTS** [comment]
Seems like the way it is currently is the correct way of going about this, it just defied my expectation. Read some data into pandas using `read_sql_query()`, the integer columns of which got cast to `int64`. Then saved to feather and expected things to just neatly be cast to integer upon read into R and had all sorts of code breakage when they got cast to double instead.

**Comment by wesm** [comment]
We should have the R coerce to double *only* when there are values outside the representable range. Because pandas defaults to int64 even for small integers this would be a better default behavior
