### ISSUE TITLE
Preserving attributes

### ISSUE THREAD

**Issue by harrelfe** [wesm/feather#222]
I hope that feather can be made to preserve all R variable attributes such as user-defined labels and units of measurement as used in the Hmisc and other packages.

**Comment by elikesprogramming** [comment]
thumbs up for this. Any plans in this direction?

**Comment by grighi** [comment]
bump. I looked into it this morning and wanted to leave a couple leads here for myself or anyone else. 

* R's .Internal [saveToConn](https://github.com/wch/r-source/blob/a7356bf91b511287aacd3a992abfbcb75b60d93c/src/main/saveload.c) uses a struct and might point out all relevant objects to be saved
* Apache arrow provides [object metadata](https://github.com/apache/arrow/blob/master/format/Metadata.md) which could store tibble attributes

**Comment by wesm** [comment]
Since the Feather codebase has now been merged into Arrow's codebase, I'm looking for R developers to help continue its development. We can continue to track Feather features on this GitHub repo. If you can get involved, I would be happy to have you

**Comment by grighi** [comment]
I think I have some capacity. How can I get in touch?

**Comment by wesm** [comment]
I am wesm AT apache DOT org, feel free to e-mail me directly or contact on the Arrow mailing list

**Comment by wesm** [comment]
@nealrichardson do we preserve attributes in the Arrow schema that's generated from converting an R data.frame?

**Comment by nealrichardson** [comment]
We don't; this may be similar to https://issues.apache.org/jira/browse/ARROW-4390. Or maybe there's something more general to do with metadata like what Pandas does?

**Comment by wesm** [comment]
We might preserve specific common attributes, like "comment"

```
> comment(df) <- "Very important data"
> attributes(df)
$names
[1] "a"

$class
[1] "data.frame"

$row.names
[1] 1 2 3 4

$comment
[1] "Very important data"
```

I'll close this. If there's sufficient interest in this then an issue in the Arrow JIRA should be opened
