### ISSUE TITLE
Error: Invalid: File is smaller than indicated metadata size

### ISSUE THREAD

**Issue by pssguy** [wesm/feather#226]
I get the above error when attempting  to read in a file with read_feather()  which I have been doing on a daily basis without issues

I believe this is probably as I have upgraded to the recent new version of feather

looking at RStudio blog, it does say feather files should not be used for long-term storage so completely my fault (although it would be a nice feature) . However, i reinstalled the 0.0.1 version and still get the same error

Is there anyways around this?

**Comment by wesm** [comment]
Can you provide a reproducible example or an example file? Also, can you give information about your platform?

**Comment by pssguy** [comment]
Thanks for swift reply. I have tried a toy example - creating in old feather version and reading back in update but cannot replicate error. The real-world file is 214MB. I was just hoping the error message would be a clue

```
library(feather) #0.0.1
library(tibble)


test_df <- tibble(a=c(1,2),b=c("a","b"))

write_feather(test_df,"problem.feather")
df <- read_feather("problem.feather")

library(feather) #0.3.0
df <- read_feather("problem.feather")
#This Feather file is old and will not be readable beyond the 0.3.0 release

# The file I want to read
df <- read_feather("data/allCranLogs.feather")
#Error: Invalid: File is smaller than indicated metadata size

sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] feather_0.3.0

loaded via a namespace (and not attached):
[1] assertthat_0.1 hms_0.2        tools_3.3.1    tibble_1.2     Rcpp_0.12.6 
```

**Comment by wesm** [comment]
Any chance you can share the real world file with me privately? It may be malformed (we fixed a number of bugs related to file handling on Windows) -- my e-mail is wesm at apache dot org

**Comment by pssguy** [comment]
I have managed to locate a slightly earlier version of this file which should save me having to recreate from scratch as it appears as though the other one did get malformed somehow.
   The real world file is very  big for email so maybe unless this issue arises again - with me or someone else - we can call it a day. Thanks again for responding on a Sunday

**Comment by wesm** [comment]
Feel free to send a Dropbox or Google Drive link if you want to share that way
