### ISSUE TITLE
feather doesn't play well with simuPOP

### ISSUE THREAD

**Issue by zkamvar** [wesm/feather#227]
Hello, 

This might be a non-issue, but I wanted to bring it to your attention in the case there are other conflicts.

I found out that I had [an issue](https://github.com/BoPeng/simuPOP/issues/3) with import order of feather ([here's a working example](https://github.com/zkamvar/simupop-example)) and another module called [simuPOP](https://github.com/BoPeng/simuPOP/). This was only an issue on Ubuntu (14.04 and 16.04), it worked fine on OSX.

If feather was imported before simuPOP, an error from simuPOP was raised. [When feather was imported after simuPOP, it was no issue](https://github.com/BoPeng/simuPOP/issues/3#issuecomment-243834067).

Here's a MWE with conda:

``` sh
conda update --all 
conda install python=3.4 
conda install -c https://conda.binstar.org/bpeng simuPOP
conda install numpy
pip install feather-format

git clone https://github.com/zkamvar/simupop-example
cd simupop-example/testpopp

# fails
python -c 'import feather;from simuPOP import *;loadPopulation("seed_0_sex_0.0000_gen_00000_rep_00.pop")'

# works
python -c 'from simuPOP import *;import feather;loadPopulation("seed_0_sex_0.0000_gen_00000_rep_00.pop")'
```

Again, I don't know if this is relevant at all, but I just wanted to bring it to your attention.

**Comment by wesm** [comment]
Can you show the error or is it a segfault? Can you post a backtrace from gdb or details of segfault from valgrind if it's a hard crash?

**Comment by zkamvar** [comment]
I can show you the error, but it doesn't come from feather:

```
$ python -c 'import feather;from simuPOP import *;loadPopulation("seed_0_sex_0.0000_gen_00000_rep_00.pop")'

simuPOP Version 1.1.7 : Copyright (c) 2004-2016 Bo Peng
Revision 5000 (May  8 2016) for Python 3.5.1 (64bit, 1thread)
Random Number Generator is set to mt19937 with random seed 0x5a2fc52bc10d2ab0.
This is the standard short allele version with 256 maximum allelic states.
For more information, please visit http://simupop.sourceforge.net,
or email simupop-list@lists.sourceforge.net (subscription required).
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/local/USDA-ARS/javier.tabima/anaconda3/lib/python3.5/site-packages/simuPOP/simuPOP_std.py", line 4739, in loadPopulation
    return _simuPOP_std.loadPopulation(file)
ValueError: Failed to load Population seed_0_sex_0.0000_gen_00000_rep_00.pop.
```

After some digging around, the source for this error is: https://github.com/BoPeng/simuPOP/blob/master/src/population.cpp#L4094-L4111:

```cpp
void Population::load(const string & filename)
{
	boost::iostreams::filtering_istream ifs;

	ifs.push(boost::iostreams::gzip_decompressor());
	ifs.push(boost::iostreams::file_source(filename, std::ios::binary));
	// do not have to test again.
	if (!ifs)
		throw ValueError("Can not open file " + filename);

	// try to load the file
	try {
		boost::archive::text_iarchive ia(ifs);
		ia >> *this;
	} catch (...) {
		throw ValueError("Failed to load Population " + filename + ".\n");
	}
}
```

I'm not terribly familiar with C++, and don't want to throw red herrings, but it looks like there might be some conflict with boost? I'm using boost version 1.49. 

Sorry if this isn't helpful :worried:

**Comment by wesm** [comment]
Yikes. That library really should be at least propagating the text of the boost exception (`e.what()`) up to the Python layer, otherwise hard to know what's happening.

**Comment by BoPeng** [comment]
I am the author of simuPOP. I came across this ticket and opened a ticket on the simuPOP side so that I can have a look later. It appears to me that there can be some reference count problem triggered by importing feather before simuPOP.
