### ISSUE TITLE
feather version - read / write capabilities

### ISSUE THREAD

**Issue by MikeBadescu** [wesm/feather#228]
Would it be possible to have a function that returns the feather file versions that the current package can read and write? Together with the file version returned by `feather_metadata` we can determine programmatically whether a certain file has an "obsolete" feather format.

**Comment by wesm** [comment]
Sounds reasonable. Will see if it can be added in a minor release. Patches welcome

**Comment by wesm** [comment]
A "version" API is available in the Feather implementation in Apache Arrow, so we could add this there if there is still interest
