### ISSUE TITLE
"this feather file is old and will not be readable" bug minimal example

### ISSUE THREAD

**Issue by jkgrain** [wesm/feather#229]
I was trying to test what happens with feather if a smaller dataframe is used to overwrite an existing feather file, but the following minimal example blows up every time.
`library(feather)
library(tibble)

df <- tibble(x=1:5, y=11:15)

write_feather(df, "test.feather")
df_read <- read_feather("test.feather")

df <- tibble(x=1:2, y=11:12)
write_feather(df, "test.feather")

df_read <- read_feather("test.feather")`

This script blows up on the last line every time.

**Comment by RoyalTS** [comment]
By "blows up" you mean that df_read is empty, I assume? This is what I get:

    > df_read
    # A tibble: 0 x 0

**Comment by jkgrain** [comment]
I get the "this feather file is old and will not be readable" error.  And then my R session aborts.

**Comment by jkgrain** [comment]
Here is a slightly different version which also has broken behavior:

`
library(feather)
library(tibble)

df <- tibble(x=1:500, y=1001:1500)

write_feather(df, "test.feather")
df_read <- read_feather("test.feather")

df <- tibble(x=1:200, y=201:400)
write_feather(df, "test.feather")

df_read <- read_feather("test.feather")

max(df_read$x)
`
max(df_read$x) returns a value of 826361158.

I think the issue comes from overwriting the existing feather file in both of my cases here. Both of these issues that I have uncovered go away if the feather file is removed prior to the second instance of writing out the file.

No where that I could find in the documentation does it talk about overwrite/append behavior of feather.

**Comment by RoyalTS** [comment]
Same issue here

    > sessionInfo()
    R version 3.3.1 (2016-06-21)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.5 (El Capitan)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] tibble_1.1    feather_0.3.0
    
    loaded via a namespace (and not attached):
    [1] lazyeval_0.2.0 assertthat_0.1 hms_0.2        tools_3.3.1    Rcpp_0.12.7

**Comment by quinnj** [comment]
I'm seeing this same behavior while trying to test various types, my script is:
```python
import feather, pandas, numpy as np, datetime

Abool = np.array([True,True,False])
Aint8 = np.array([1,1,0], dtype=np.int8)
Aint16 = np.array([1,1,0], dtype=np.int16)
Aint32 = np.array([1,1,0], dtype=np.int32)
Aint64 = np.array([1,1,0], dtype=np.int64)
Auint8 = np.array([1,1,0], dtype=np.uint8)
Auint16 = np.array([1,1,0], dtype=np.uint16)
Auint32 = np.array([1,1,0], dtype=np.uint32)
Auint64 = np.array([1,1,0], dtype=np.uint64)

Afloat32 = np.array([1.0, "NaN", 0.0], dtype=np.float32)
Afloat64 = np.array(["Inf", 1.0, 0.0], dtype=np.float64)

Autf8 = ["hey","there","sailor"]
Abinary = [b"hey",b"there",b"sailor"]

Adate = [datetime.datetime(2016,1,1).date(),datetime.datetime(2016,1,2).date(),datetime.datetime(2016,1,3).date()]
Adatetime = [None,datetime.datetime(2016,1,2),datetime.datetime(2016,1,3)]

Acat = pandas.Categorical(["a","b","c"], categories=["b","c","d"],ordered=False)
Acatordered = pandas.Categorical(["d","e","f"], categories=["d","e","f"],ordered=True)

df = pandas.DataFrame({"Abool": Abool,"Aint8": Aint8,"Aint16": Aint16,"Aint32": Aint32,"Aint64": Aint64,"Auint8": Auint8,"Auint16": Auint16,"Auint32": Auint32,"Auint64": Auint64,"Afloat32": Afloat32,"Afloat64": Afloat64,"Autf8": Autf8,"Abinary": Abinary,"Adatetime": Adatetime,"Acat": Acat,"Acatordered": Acatordered})

feather.write_dataframe(df, "test.feather")
df2 = feather.read_dataframe("test.feather")
```

with output of:
```python
>>> df
     Abinary  Abool Acat Acatordered  Adatetime  Afloat32  Afloat64  Aint16  \
0     b'hey'   True  NaN           d        NaT       1.0       inf       1
1   b'there'   True    b           e 2016-01-02       NaN  1.000000       1
2  b'sailor'  False    c           f 2016-01-03       0.0  0.000000       0

   Aint32  Aint64  Aint8  Auint16  Auint32  Auint64  Auint8   Autf8
0       1       1      1        1        1        1       1     hey
1       1       1      1        1        1        1       1   there
2       0       0      0        0        0        0       0  sailor
>>> feather.write_dataframe(df, "test.feather")
>>> df2 = feather.read_dataframe("test.feather")
This Feather file is old and will not be readable beyond the 0.3.0 release
Segmentation fault: 11
```

**Comment by ralexx** [comment]
Similar behavior under Python 3.5.2, Feather 0.3.0 reading a file created with Feather 0.2.0.

```shell
>>> import feather
>>> myfile = 'mydir/tests/timeseries_data.feather'
>>> df = feather.read_dataframe(myfile)
This Feather file is old and will not be readable beyond the 0.3.0 release
fish: 'python3' terminated by signal SIGSEGV (Address boundary error)
```
OS X crash log: [python3.5_2016-09-12-175624_macpro.txt](https://github.com/wesm/feather/files/468703/python3.5_2016-09-12-175624_macpro.txt)

**Comment by wesm** [comment]
If you can reproduce this with `arrow::read_feather` would you please open a new issue in http://issues.apache.org/jira?
