### ISSUE TITLE
Read dataframe from a URL

### ISSUE THREAD

**Issue by dhimmel** [wesm/feather#231]
Similar to how `pandas` and `readr` can read a dataframe from a URL, it would be convenient to be able to supply a URL to `feather.read_dataframe`.

**Comment by dhimmel** [comment]
The python implementation will likely depend on resolving https://github.com/wesm/feather/issues/203.

**Comment by wesm** [comment]
Please open an issue in Apache Arrow if you'd like to implement this functionality there (we have full URI support and other things that will help)
