### ISSUE TITLE
Deprecations in pandas 0.19 means moving to the public API 

### ISSUE THREAD

**Issue by chrisaycock** [wesm/feather#235]
`pandas.core.common.is_categorical_dtype` -> `pandas.api.types.is_categorical_dtype`

`pandas.core.common.is_datetime64_any_dtype` -> `pandas.api.types.is_datetime64_any_dtype`

**Comment by guillett** [comment]
@wesm it looks like this issue can be closed as the fix was contained and merged from #242.
