### ISSUE TITLE
New feather format

### ISSUE THREAD

**Issue by Diego-MX** [wesm/feather#248]
Okay, I'm gonna use this channel to raise an unlucky situation.  
While I understand this is an open tool, and am using it under my risk.  There is also an issue to be fixed, and hopefully this helps the developers to prevent this situation. 

I've used the feather package for about two months.  For interaction with the server, I updated the package, and resulted that the previous files were old.  

I decided to get rid of the warning messages by doing:  `read_feather -> write_feather`.  
The rewritten feather files now gives me a warning:
`Error: Invalid: Feather file footer incomplete`

And now I have to regenerate the files from the very beginning.  Unlucky me. 
I tried reproducing the error, but wasn't able to because I've updated the package, and I believe this was due to some changes made in the package. 

Has this happened to others?  Is there a fix for it?  
Thank you.

**Comment by wesm** [comment]
There is a bug in which overwriting files does not do the right thing. Help fixing this bug would be very much appreciated

**Comment by inkrement** [comment]
@wesm is it somehow possible to recover these files? Do you already work on a fix?...

**Comment by wesm** [comment]
I believe this has been fixed in Feather 0.4.0

**Comment by justinesjw** [comment]
Hi @Diego-MX ! 

I'm facing the same error 

![image](https://user-images.githubusercontent.com/26448066/59084899-6b68a880-892f-11e9-8cf2-21c3b9b82b63.png)

May I know how you solve the problem? 

and also, I might be missing something, but isn't feather 0.4.0 for python? does it work for SCENIC on R?

Thanks!!
