### ISSUE TITLE
Fix requirements in python package

### ISSUE THREAD

**Issue by j-santander** [wesm/feather#256]
Must include cython and numpy as dependencies to the python package.

Otherwise, installing feather-format, stand-alone or as a dependency will fail even in the case that both dependencies are provided at the same time

The work-around is a two step installation, first install cython and numpy and then install feather-format... but this is an unnecessary complication and prevents from creating a package depending on feather-format.

Steps to reproduce:

```
$ virtualenv test
New python executable in /home/jsantand/test/bin/python
Installing setuptools, pip, wheel...done.
(test)
$ . test/bin/activate
(test) $ pip install feather-format
Collecting feather-format
  Using cached feather-format-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YX2BgL/feather-format/setup.py", line 19, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YX2BgL/feather-format/
```

**Comment by wesm** [comment]
Can you please submit a PR?

**Comment by wesm** [comment]
Closing as outdated
