### ISSUE TITLE
[Python] Add DataFrame index metadata and additional index columns, where relevant

### ISSUE THREAD

**Issue by wesm** [wesm/feather#258]
We could use a unique identifier for index columns and add table-level metadata to indicate that a particular column is the index / row names. Same strategy could work for non-string column names

**Comment by tkelman** [comment]
Would this involve doing something about the `preserve_index` flag round about here?
https://github.com/apache/arrow/blob/e3db5da648bb74b3d325042e595ae856f1ad8f7f/python/pyarrow/feather.py#L80

**Comment by wesm** [comment]
We would want to use the strategy we're currently employing for preserving the index in general Arrow streams. Hopefully we'll have R bindings for Arrow sometime in the next year, so we can deprecate the Feather metadata

**Comment by orenbenkiki** [comment]
It was a surprise for me that feather does not preserve the rows index of the data frame. That is:
```python
import feather
import pandas

written = pandas.DataFrame({'a': [1, 2], 'b': [3, 4]}, index=['x', 'y'])
print('written')
print(written)
with open('feather', 'wb') as file:
    feather.write_dataframe(written, file)
with open('feather', 'rb') as file:
    read = feather.read_dataframe(file)
print('read')
print(read)
print('equals')
print(read.equals(written))
```
Prints:
```
written
   a  b
x  1  3
y  2  4
read
   a  b
0  1  3
1  2  4
equals
False
```
It seems arbitrary that column names are preserved but row names are not. Is this the intentional behavior? Are there any plans for preserving the row names as well?

**Comment by wesm** [comment]
We support this well in Arrow serialization, but just haven't done it here yet. Once Feather is shipping in R as provide by the Arrow C++ libraries, we can revisit this

**Comment by wesm** [comment]
We'll be decommissioning the R implementation here and changing `feather` to use `arrow` internally in the near future
