### ISSUE TITLE
Installation on Lubuntu 16.04 with MRO 3.3.1 in Rstudio

### ISSUE THREAD

**Issue by cxu60** [wesm/feather#259]
I tried to install feather by 
`install.packages('feather')`
The dependencies compiled and were linked perfectly. But feather itself failed to compile with first error as follows
`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -DU_STATIC_IMPLEMENTATION -I"/home/cxu60/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`
I think the problem is coming from the letter "I" prepending to the path. I just got no idea where this letter comes from?

**Comment by kevinushey** [comment]
This can occur if R was compiled with an older gcc (e.g. one for which R does not detect C++11 support).

The easiest fix is to add the following to your `~/.R/Makevars` file:

```
CXX1X=gcc -std=c++0x
CXX1XSTD=-std=c++0x
```

**Comment by blueogive** [comment]
I'm running Microsoft R Open 3.3.2 under Linux and encountered the same problem. The fix proposed by @kevinushey worked for me, except that I also had to add the -fPIC option to `~/.R/makevars` like this:

    CXX1X=gcc -std=c++0x -fPIC
    CXX1XSTD=-std=c++0x

**Comment by kevinushey** [comment]
Note that by default R builds include `-fPIC` for `CXXFLAGS` and friends (from the `configure` script), so I'm not sure why this isn't the default for Microsoft R Open.

**Comment by wesm** [comment]
won't fix
