### ISSUE TITLE
Fall-back type (string) for un-supported feather data type.

### ISSUE THREAD

**Issue by BoPeng** [wesm/feather#261]
As reported by other users (e.g, #121, #174), feather can fail to handle unrecognized data types. Because it is not always possible to find equivalent datatypes between R and Python, this error will persist, and prevent data communication between Python and R, even if only one irrelevant column is causing the problem.

I therefore propose that, instead of raising an exception, feather would create a column with string representation of the data. A warning message could be given but the majority of the data would still be passed, and the column with unknown type can most-likely still be handled with some post-processing.

**Comment by nickteff** [comment]
I am having the same issue as @BoPeng 

    Traceback (most recent call last):

      File "<ipython-input-12-bdaa278c0c13>", line 1, in <module>
        df = feather.read_dataframe('modelingWIP.feather')

      File "C:\Users\nteff\AppData\Local\Continuum\Anaconda3\lib\site-packages\feather\api.py", line 93, in read_dataframe
        arr = col.read()

      File "feather/ext.pyx", line 225, in feather.ext.Column.read (feather/ext.cpp:3841)

    NotImplementedError: 3

**Comment by wesm** [comment]
This should be addressed by the Arrow-based Feather implementation
