### ISSUE TITLE
decouple from tibble - support R-3.1.1

### ISSUE THREAD

**Issue by dlpd** [wesm/feather#262]
Apologies if this is the wrong forum for this comment.

Feather has been a godsend for me and would be ubiquitous in my work, however its coupling with tibble prevents that. The issue isn't with tibble per se - though tibble seems like sugar and is unrelated to feather's core concern. However, tibble only supports >= R-3.1.2 and for legacy reasons I'm locked into R-3.1.1.

Feather itself doesn't require R-3.1.2 and I don't see anything in the 3.1.2 [changelog](https://stat.ethz.ch/pipermail/r-announce/2014/000578.html) that seems relevant. As far as I can tell, excising the tibble imports and tibble::as_data_frame everything would still just work.

Is it feasible to suggest tibble and not lock out those stuck with R-3.1.1?

**Comment by krlmlr** [comment]
Would you mind filing an issue with tibble to support R >= 3.0.0?

**Comment by dlpd** [comment]
Thanks for the quick reply!

That doesn't really address my concern - the point is why couple feather unnecessarily? Even if tibble supported R-3.1.1, it's still one extra dependency that seems totally unnecessary.

In our workflow we convert to data.table immediately after feather::read_feather. Others may prefer to use tibble or even just data.frame. For feather to become a "standard" - which would great! - why force that decision?

**Comment by krlmlr** [comment]
That's a good point. Tibbles print nicer and lose some of the problems data frames have, but ultimately this is up to @hadley to decide.

**Comment by hadley** [comment]
I very strongly believe that for most R users, tibbles are a substantial improvement over data frames. 
Why are you immediately coercing to data frames?

**Comment by dlpd** [comment]
We coerce to data.table. Let's not debate the merits of tibble itself - on which I'm agnostic - our use case is part of a larger ecosystem, which for better or worse we're locked in.

Dependencies are _constraints_ on who can use your package. Some are necessary, some are harmless and constrain no one; like everything it's a tradeoff. Hopefully we can agree that tibble is not strictly _necessary_. At least for us it's not harmless.

Why not simply suggest tibble and only convert if it's installed? I'm happy to submit a PR implementing.

**Comment by hadley** [comment]
Why can't you convert directly to data.tables from tibbles?

I agree that tibble is not absolutely necessary for experienced R developers, but it makes a big difference to new users. (And I find it extremely frustrating when I accidentally print a large data frame and my session is locked up for 5 minutes, so from that perspective tibbles are important for the sorts of larger datasets you might be storing with feather).

Changing behaviour based on whether or not a package is installed is a recipe for hard to track down bugs.

**Comment by dlpd** [comment]
> Why can't you convert directly to data.tables from tibbles?

Because we can't even use tibble as it requires >= R-3.1.2. Thus we can't use feather either. I assume tibble's is incompatible with R-3.1.1 - as per its DESC. - but you'd obviously know better than I how necessary that really is.

As @krlmlr suggested I could file an issue for tibble - and then whatever tibble depends on, etc. - but that's a deep rabbit hole to go down. And even then, what about users stuck with R-3.0.*? Restricting feather's adoption b/c of concern over new users learning an unrelated, (hopefully) one-off lesson about the "horrors" of printing data.frame's seems like a poor tradeoff.

> Changing behaviour based on whether or not a package is installed is a recipe for hard to track down bugs.

Agreed. I only suggested this as feasibly middle ground. IMHO the cleanest solution is to de-couple with tibble and let the user decide.

**Comment by hadley** [comment]
I think you're making a strong assumption about the compatibility of feather with older versions of R  (disregarding the indirect dependency via tibble). We could definitely push back to 3.1.0 (3.0.0 is probably too far to be worth it) with some testing and minor fixes, but I'm not really interested in dropping the tibble dependency.

**Comment by dlpd** [comment]
> We could definitely push back to 3.1.0

That would solve my immediate concern, so selfishly is a sufficient goal.

> I'm not really interested in dropping the tibble dependency

That's your prerogative. I won't try to change your mind further, though I do wonder if this is with feather's best interests in mind or a desire to cross-promote another package.

As the maintainer of both, how should I proceed? Do you want me to submit an separate issue to tibble?

**Comment by hadley** [comment]
Yes, an issue on tibble would be the way forward.

**Comment by hadley** [comment]
I may change my mind about the tibble issue, but currently I'm being fairly aggressive because I believe it helps the vast majority of R users, and it's worth some frustration/hassle in the short term.

**Comment by clarkfitzg** [comment]
+1 for no tibble dependency

**Comment by kendonB** [comment]
Why not add a non-exported function that can read to ``data.frame``? This way it would be completely hidden from new users who might otherwise accidentally use it. To me, this is the best of both worlds - old R users get the choice and noobs are protected from the perils of using base data.frames.

**Comment by hadley** [comment]
Because that encourages people to use non-exported functions which is a very bad thing.

I'm going to close this issue for now, as I don't think further discussion is helpful.
