### ISSUE TITLE
Allow saving to compressed files

### ISSUE THREAD

**Issue by ostrokach** [wesm/feather#264]
Is there any way to use gzip (or bzip2 or xz) compression when saving a pandas DataFrame to a feather file? Something like `feather.write_dataframe(df, path, compression='gzip')`, the way you can do with `DataFrame.to_csv(...)`?

I work a lot with files stored on an NFS network drive, and `feather.write_dataframe` stresses our network and creates files which are much larger than the equivalent gzip-compressed CSVs. I tried running `gzip -9` on a feather file and got ~10x reduction in size.

I know compression has been mentioned already (#24, #76), but those seem to deal with changing the feather format to support block compression. I just want to gzip the entire file *at the same time* as I am saving it (and not afterwards using `gzip`).

Thank you!

**Comment by wesm** [comment]
It would be great for someone to contribute lz4 or zstd (or gzip, sure) buffer compression as an option. There's a very limited number of places where work would need to be done (see the places where bytes are written in the writer class):

https://github.com/wesm/feather/blob/master/cpp/src/feather/writer.cc#L106

**Comment by wesm** [comment]
(This is a significantly better option than gzipping the whole file, as you'll still be able to inspect the metadata and read individual columns from the file. Also reads can be performed in parallel if someone wants to add that)

**Comment by kljensen** [comment]
Wes, are there homologous implementations in the wild to which you can
point? E.g. in bcolz or similar? I'd enjoy working on this.

**Comment by xhochy** [comment]
Have a look at Parquet:
 * https://github.com/apache/parquet-cpp/blob/master/src/parquet/column/writer.cc#L124
 * https://github.com/apache/parquet-cpp/tree/master/src/parquet/compression

**Comment by fbrundu** [comment]
Hi all,
are there updates on this feature?
Thanks

**Comment by wesm** [comment]
hi @fbrundu we've set up the compression toolchain within Apache Arrow and I'm standing by to add compression to the Feather format as soon as we are able to ship R bindings for the Arrow C++ libraries (and port over the data.frame conversion code from this repo there as part of the R-Arrow interop layer)

**Comment by itssimon** [comment]
Any updates on this @wesm ?

**Comment by wesm** [comment]
We hope to get to this in 2018 as part of the new Ursa Labs effort (https://ursalabs.org/), which will be helping build R bindings for Apache Arrow. Then it will be reasonably straightforward to develop the next iteration of the Feather format featuring compression, random access APIs, and other oft-requested features.

**Comment by wesm** [comment]
Your contributions to this effort, of course, would be most appreciated

**Comment by ma3axaka** [comment]
@wesm I'll be glad to contribute this feature if everything's already in place from the Arrow side. But I need a quick overview what needs to be done.

**Comment by wesm** [comment]
I suggest we discuss on the Arrow mailing list

**Comment by rgeronimi** [comment]
Hi any news on this? The feather format is incredibly fast and useful, this is the only real feature missing.
Note: ability to customize/plug in a different compression format than gzip would be a great plus (zstandard has incredible compression capabilities and we are now using it everywhere)

**Comment by wesm** [comment]
I suggest following https://issues.apache.org/jira/browse/ARROW-5510 or discussing more on the dev@arrow.apache.org mailing list. I agree that having compression would be a big help but there are very few individuals who have volunteered time to work on this

**Comment by wesm** [comment]
This is done in Feather V2 (lz4 and zstd compression available) coming in Arrow 0.17.0
