### ISSUE TITLE
segfault opening old data file (R)

### ISSUE THREAD

**Issue by tdsmith** [wesm/feather#266]
Attempting to read a small but old feather file triggers a segfault.

Crasher: https://dl.dropboxusercontent.com/u/3720/junk/crasher.feather

R session output:
```
This Feather file is old and will not be readable beyond the 0.3.0 release

 *** caught segfault ***
address 0x10e024b23, cause 'memory not mapped'

Traceback:
 1: .Call("feather_coldataFeather", PACKAGE = "feather", feather,     indexes)
 2: coldataFeather(x, i)
 3: `[.feather`(x, )
 4: x[]
 5: as_data_frame.feather(data)
 6: as_data_frame(data)
 7: feather::read_feather(target)
```

```
> devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin16.1.0        
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-11-30                  

Packages ----------------------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.1     2013-12-06 CRAN (R 3.3.0)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 feather    * 0.3.1   2016-11-09 CRAN (R 3.3.2)
 hms          0.2     2016-06-17 CRAN (R 3.3.1)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.0)
 Rcpp         0.12.8  2016-11-17 CRAN (R 3.3.2)
 tibble       1.2     2016-08-26 cran (@1.2)   
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)
```

**Comment by tdsmith** [comment]
this may echo some of the complaints in #229, which looks sort of heterogenous

**Comment by wesm** [comment]
Note we've never made any explicit guarantees of backwards compatibility, only best efforts. I'll take a look at the file to see if there's something obvious wrong

**Comment by tdsmith** [comment]
I'm more concerned by the segfault; I don't mind if this throws an error but I think it shouldn't crash.

**Comment by wesm** [comment]
This file is significantly corrupted -- it appears to have been written to multiple times. 

```python
In [19]: f = open('/home/wesm/Downloads/crasher.feather', 'rb')

In [20]: data = f.read()

In [21]: data.count(b'FEA1')
Out[21]: 13
```

`FEA1` is the magic number that marks the beginning and end of a feather file.

We fixed a bug in Feather 0.3.1 that resulted in file corruption in earlier versions when writing to a file name that already exists.

**Comment by tdsmith** [comment]
I expected that libfeather should not segfault on malformed input; is that
unrealistic?

**Comment by wesm** [comment]
It is unrealistic given the file format as it stands. C and C++ are not memory safe languages, so segfaults are a reasonable expectation is you feed corrupted input into an algorithm. One recourse would be to add a md5 checksum to the file metadata, but computing a full file checksum in order to be granted permission to read the rest of the file is pretty onerous. It may be possible to add some other rudimentary checks, but they would be ad hoc checks against the kinds of bugs that we fixed in this release (e.g. https://github.com/wesm/feather/commit/f120c392ef5afc57d38c450f0f78f3c59fc11f05).

If you have any other suggestions about how to solve the problem without adding significant performance overhead, I'm happy to take a look

**Comment by tdsmith** [comment]
It seems possible that this sort of failure creates opportunities for arbitrary code execution upon parsing a feather file, which would make feather inappropriate for data exchange between any but completely trusted parties, which would be an unfortunate limitation.

**Comment by wesm** [comment]
Patches or design proposals are most welcome
