### ISSUE TITLE
module object has no attribute 'write_dataframe'

### ISSUE THREAD

**Issue by Data-drone** [wesm/feather#267]
I got feather 0.9.1.dev0 installed and when I try to use

```
import feather
import pandas as pd
test = pd.DataFrame([1,2,3,4], columns = ['test'])
feather.write_dataframe(test, 'my_object.feather')
```

as per the instructions here: https://blog.rstudio.org/2016/03/29/feather/
I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'write_dataframe'
```

**Comment by wesm** [comment]
Did you `pip install feather` or `pip install feather-format`?

**Comment by wesm** [comment]
This is not the feather you are looking for: https://pypi.python.org/pypi/feather
