### ISSUE TITLE
ImportError on `import feather` (Ubuntu 16.04, python 3.5)

### ISSUE THREAD

**Issue by shivam6294** [wesm/feather#268]
I'm getting the following error when trying to `import feather`
 

`ImportError: /home/ubuntu/anaconda3/lib/python3.5/site-packages/feather/ext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
`

Using Ubuntu 16.04, gcc version 5.4.0, and python 3.5

Steps taken to install:
1. activate anaconda virtual environment
2. pip install feather-format
3. import feather

**Comment by wesm** [comment]
I suggest you install from conda forge `conda install feather-format -c conda-forge`

On gcc 5.x, you will need to add a compiler flag (e.g. via environment variable) that disables the GCC5 ABI. In general, any C++ code you compile with your system gcc for use in Anaconda is going to have this problem

**Comment by HEHenson** [comment]
Thanks for the tip.  I had the same problem and it worked for me.

**Comment by wesm** [comment]
The Feather Python implementation has moved to pyarrow; there are now conda packages and binary wheels for Linux, so this problem should be gone with the Feather 0.4 release

**Comment by HEHenson** [comment]
Thank you for letting me/us know
