### ISSUE TITLE
Slightly confusing error messages with unsupported data?

### ISSUE THREAD

**Issue by erikcs** [wesm/feather#270]
Say you run

```python
import numpy as np
import pandas as pd
import feather

df = pd.DataFrame({'nope': np.array([2.0, 3.5], dtype=np.float16)})
feather.write_dataframe(df, 'test.feather')
```

this raises `FeatherError: Invalid: unsupported type 23` ( The corresponding error for the same offense in the `julia` wrapper is `LoadError: KeyError: key Float16 not found`)

if you run 

```python
df = pd.DataFrame({'nope': np.array([np.nan, np.nan], dtype=np.object)})
feather.write_dataframe(df, 'test.feather')
```

you get `ValueError: cannot serialize column 0 named nope with dtype floating`. (in `julia`: `LoadError: argument is an abstract type; size is indeterminate`)

In the first case, I would be at fault for not realising that the [list of supported column types](https://github.com/wesm/feather) does not include `Float16`. The second case is very contrived, but happened to pop up when I foolishly tried to convert a messy CSV to feather without cleaning it first, and at first glance that column looked like a float. 

My point was just if you get error messages like these on a large dataframes, it can be hard to pinpoint the offending column and what the problem is. In the python wrapper [check_status](https://github.com/wesm/feather/blob/master/python/feather/ext.pyx#L52) could maybe print the offending column name? (Perhaps the different wrappers could harmonize the error messages?)  Sorry if this is just me being slow (please close this issue if so).

**Comment by wesm** [comment]
Definitely it would be good to make the Python error messages better. I don't have time to look into it right now, but patches definitely welcome

**Comment by nuffe** [comment]
Regarding the first error message, would an alternative to the brief `unsupported type` in [interop.h](https://github.com/wesm/feather/blob/master/python/feather/interop.h#L452) be something something like `Unsupported data type (NPY_TYPES enum value: ...). Please refer to the Feather webpage for a list of supported column types` ?

(tracing down the "offending" column name by littering [check_status](https://github.com/wesm/feather/blob/master/python/feather/ext.pyx#L52) with optional column name arguments seem very messy?)

Regarding the last error message, this is just a "pathological" column type that warps the data type inference logic in [api.py](https://github.com/wesm/feather/blob/master/python/feather/api.py#L42):

```python
from feather.compat import pdapi
import pandas as pd
import numpy as np

col = np.array([0.1, 0.1], dtype=np.object)

pdapi.is_object_dtype(col)
# True

inferred_type = pd.lib.infer_dtype(col)
inferred_type
# 'floating'
```

I am not sure what a good fix for this would be?

**Comment by wesm** [comment]
This should be addressed by the `pyarrow`-based Feather implementation
