### ISSUE TITLE
Documentation: basic C++ howto and data structures description

### ISSUE THREAD

**Issue by vspinu** [wesm/feather#271]
Is there any user level documentation out there on the underlying data structure and supported operations? Or the C++ codebase is the only "doc" at the moment?  Particularly, what data types are supported and how they are stored, and what kind of random access read/write operations are supported (extracting columns, appending columns, extract or write an indexed range of columns etc).  

Would be nice have a basic "hello world" example of how to operate on metadata and read and write all supported data types from C++.  And maybe a high level meta discussion of what problems the format solves and how it concretely relates to "arrow" project would be very much appreciated. 

Thank you.

**Comment by vspinu** [comment]
After spending a couple of hours looking into the code base I am partially answering my own question.

There is a basic description of the storage types [here](https://github.com/wesm/feather/blob/master/doc/FORMAT.md). That is helpful, but there is no provision there for how lists and string vectors should be stored. Both are aparently stored as ad hoc var length arrays. 

The core C++ is a low level interface and no C++ front end is available. So If I want to use `feather` in my C++ app I would need to re-implement a good part of the logic from [R's front end](https://github.com/wesm/feather/tree/master/R/src). 

As to the modification and access types there is not much to document. AFAICS the core api doesn't allow for in-file modification. One can read arbitrary column in but there is no provision for reading subranges. One can append columns to an open stream, but there is no way to re-write an existent column in a file.

**Comment by wesm** [comment]
> Both are aparently stored as ad hoc var length arrays.

There are a number of different ways to store variable-length arrays, the one we are using is definitely not ad hoc:

* See https://github.com/wesm/feather/blob/master/doc/FORMAT.md#variable-length-arrays
* and https://github.com/apache/arrow/blob/master/format/Layout.md#list-type

I would welcome some improvements like you are describing to the core libfeather library -- I only did enough C++ engineering to support the initial Python and R use cases (write a table, read a table).

**Comment by wesm** [comment]
The C++ code has moved to the Apache Arrow codebase https://github.com/apache/arrow/tree/master/cpp/src/arrow/ipc, so we can address more work on the C++ code there
