### ISSUE TITLE
Row by row streaming

### ISSUE THREAD

**Issue by vspinu** [wesm/feather#272]
My use case involves reading data frames row by row from C++. From what I have dug so far such functionality would be difficult to build upon feather. There is no support for streaming in flattbuffers and arrow layout is column based which presumably(?) rules out efficient row by row access.  

Any thoughts?

**Comment by wesm** [comment]
You could read (columnar) batches and then iterate through them row by row. Since pandas and R are mostly column oriented it was a reasonable tradeoff for these use cases.

**Comment by wesm** [comment]
Feather V2 with configurable chunk sizes and batch-based reading is coming in Arrow 0.17.0, so closing this
