### ISSUE TITLE
[Python] 0.3.1 regression or confusing error message?

### ISSUE THREAD

**Issue by rgrinberg** [wesm/feather#274]
The following snippet:

```
import pandas as pd
import feather

feather.write_dataframe(pd.DataFrame({'c': [True]}, dtype='object'), "xxx.feather")
```

Will yield the following error in 0.3.1 but no error 0.3.0:

```
cannot serialize column 0 named c with dtype boolean
```

I guess I can see how the change in 0.3.1 added validation against such imprecise dtypes. But it still seems like it should either give a better message (that dtype is actually object) or still allow the more general type here.

**Comment by jreback** [comment]
https://github.com/wesm/feather/issues/240

in general you cannot serialize ``object`` dtypes when they are not string/unicode. IOW, you cannot actually handle actual python references. So this is fine as a ``bool`` type, but not as an ``object`` dtype.

I suppose the error message you be even more explicit.

**Comment by wesm** [comment]
This should be fixed now
