### ISSUE TITLE
issue on long int

### ISSUE THREAD

**Issue by zheguzai100** [wesm/feather#276]
my dataset has a col1
class(col1)=='integer64'
head(col1,3)
5914855887
5914855887
5914855887

but after write_feather(), and read back, it turns into 
2.922327e-314
2.922327e-314
2.922327e-314

why it happens and how to aviod it ????

**Comment by samuelcrane** [comment]
I'm experiencing the same. 

`class(d$count)`
[1] "integer64"

`head(d$count)`
integer64
[1] 105462 105917 111992 45825  110496 112862

```
write_feather(d, "int64_test.feather")
d2 <- read_feather("int64_test.feather")
```

`class(d2$count)`
[1] "numeric"
`head(d2$count)`
[1] 5.210515e-319 5.232995e-319 5.533140e-319 2.264056e-319 5.459228e-319 5.576124e-319

**Comment by wesm** [comment]
I think this should be fixed in the `arrow` package. We are working toward `feather` using `arrow` internally, should be done in the near future
