### ISSUE TITLE
Single-writer Multiple-readers

### ISSUE THREAD

**Issue by mike-lawrence** [wesm/feather#281]
HDF5 has the ability to have a single-writer and multiple-readers ("swmr"), which is very useful for scenarios where you have one process receiving a data stream that you want to get on disk as fast as possible but also have several other processes monitoring the incoming data (ex. one visualizing the raw feed, one doing realtime signal detection stuff, etc). It would be great if feather could support this too.

**Comment by wesm** [comment]
This doesn't have too much to do with HDF5 per se -- the Feather format currently does not permit updates or appends to an existing data set. You could hypothetically store Feather data in HDF5 and utilize it in a SWMR setting. I would welcome this sort of engineering work (it would probably fit best within Apache Arrow itself)
