### ISSUE TITLE
Ruby bindings for Feather?

### ISSUE THREAD

**Issue by arbox** [wesm/feather#282]
Not an issue rather a question :)
Are there any plans on implementing feather bindings for Ruby?

**Comment by xhochy** [comment]
This mainly boils down to if someone is willing to implement the [Apache Arrow](https://github.com/apache/arrow) memory structures for Ruby. Once you have implemented those, you've got Feather support. 

Out of curiosity: Is there an equivalent / some similar to Pandas DataFrames in Ruby?

**Comment by arbox** [comment]
Ok, I understand, thank you @xhochy 

I somebody could answer my silly questions at the beginning I could implement this.

Daru is the ongoing project with the similar functionality to Pandas: https://github.com/SciRuby/daru

**Comment by arbox** [comment]
An update to this issue: @kou is working on Apache Arrow binding for Ruby, and the Red Arrow project gets soon the compatibility with Feather: https://github.com/red-data-tools/red-arrow/issues/1

**Comment by wesm** [comment]
Closing since these files can be read and written from red-arrow in Ruby
