### ISSUE TITLE
error writing python bytes type

### ISSUE THREAD

**Issue by wcbeard** [wesm/feather#283]
I get an error when trying to write a df with bytes in the column (strings cause no issue):
```
d = DataFrame([b'abc'], columns=['A'])
feather.write_dataframe(d, '/tmp/x.fth')
=> ValueError: cannot serialize column 0 named A with dtype bytes
```

Not sure if it's a bug or intentional design. On the python [readme](https://github.com/wesm/feather/blob/master/python/README.md), it says a limitation of the project is

> Object-type columns with non-homogeneous data

but that doesn't seem to apply here.

```
Pandas 0.19.2
feather 0.3.1
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
```

**Comment by d10genes** [comment]
Oddly, adding a null value to the column succeeds in writing (`DataFrame([b'abc', np.nan], columns=['A'])`)

**Comment by wesm** [comment]
Should be addressed by the `pyarrow`-based Feather implementation
