### ISSUE TITLE
Cannot read non- utf-8 encoded data. 

### ISSUE THREAD

**Issue by epinephelus** [wesm/feather#285]
I wrote a dataframe with non utf-8 characters from R. When trying to read it in Python, I get a UnicodeDecodeError.

`---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 10: invalid continuation byte

During handling of the above exception, another exception occurred:

SystemError                               Traceback (most recent call last)
<ipython-input-511-d4bc305eab3d> in <module>()
----> 1 df = feather.read_dataframe("../../data/Data/data.feather")

/Users/konstantinos.tsakali/.local/lib/python3.5/site-packages/feather/api.py in read_dataframe(path, columns)
     91         name = col.name
     92         if columns is None or name in columns:
---> 93             arr = col.read()
     94             data[name] = arr
     95             names.append(name)

SystemError: <built-in method read of feather.ext.Column object at 0x133dcce08> returned a result with an error set`

**Comment by wesm** [comment]
Yes, this is a bug in the Feather-Python bindings. I hope to resolve this and a host of other issues within the next 1-2 months, so stay tuned

**Comment by ameintjes** [comment]
Has anyone found a workarounds for this?

**Comment by gansanay** [comment]
Just tried to reproduce this one. I used:

* feather 0.3.1 for R
* feather 0.4.0 for Python
* pyarrow 0.6.0

Code:

```R
library(feather)
years <- c(1980, 1985, 1990)
labels <- c('è', 'à', 'ù')
df <- data.frame(years, labels)
write_feather(df, "0e8.feather")
```

```python
import feather
feather.read_dataframe('0e8.feather')
```
| years | labels
| -- | --
1980.0 | è
1985.0 | à
1990.0 | ù

@wesm probably fixed this one.

**Comment by wesm** [comment]
Yep, I believe I did. Closing this issue
