### ISSUE TITLE
[Feature Request] function to write to string

### ISSUE THREAD

**Issue by robinsonjj** [wesm/feather#291]
It would be great if there was an option to write a string representation of the bytes so that dataframes could by easily sent through a message broker between python and R

**Comment by xhochy** [comment]
At least for the Python side of things, this feature will automatically come with the merge of Feather into the Apache Arrow codebase: https://github.com/apache/arrow/pull/361

**Comment by wesm** [comment]
Yes, this should be relatively easy now. I'll leave this open since we should create an upstream JIRA and add a unit test for this. Patches welcome

**Comment by wesm** [comment]
This is addressed by the `pyarrow`-based implementation now
