### ISSUE TITLE
data.table integration

### ISSUE THREAD

**Issue by txn123** [wesm/feather#293]
writing fails when a large data.table (100GB)  is used - I suspect it is because the package is working with it as a data.frame - do you plan to change it any time soon ?

**Comment by jameslamb** [comment]
@txn123 Have you seen [this open PR](https://github.com/wesm/feather/pull/294)? Your case may not be specific to a particular R object type, but you may just be hitting the upper limit on column size.

**Comment by wesm** [comment]
This is fixed in "Feather V2" that's part of the upcoming Apache Arrow 0.17.0 release
