### ISSUE TITLE
subset behaves strangely with feather

### ISSUE THREAD

**Issue by jllipatz** [wesm/feather#298]
Hello,

I don't know if the 'subset' function is supposed to work or not on feather files opened with the function 'feather' but I get different behaviours that are not very explicit. It looks like some method is inconstently implemented.

Example 1 (original is a data frame):
  data(iris)
  write_feather(iris,"U:/R/iris.feather")
  f<-feather("U:/R/iris.feather")
  subset(f,Species=="setosa")
results  in: 
Error in subset.default(f, Species == "setosa") : 
  objet 'Species' introuvable

Example 2 (original is a tibble):
  b<-read_sas("U:/R/bsa2003.sas7bdat")
  write_feather(b,"U:/R/bsa2003.feather")
  f<-feather("U:/R/bsa2003.feather")
  subset(f,DEP=="86")
succeeds, but selects only one column (the DEP column), while a subset on the original 'b' returns the whole 28 columns of the data set.

Best regards
Jean-Luc LIPATZ

**Comment by gansanay** [comment]
Hi Jean-Luc,

The object you get from using `feather()` is a Feather store. If you want to get a data.frame, you should use `read_feather()`. Subsetting should then work as expected. I tested it on the iris dataset.

Tell me if it works on the tibble you have too.

Regards,
Guillaume
