### ISSUE TITLE
Timestamp, Time, Date, and Category types values aren't written to disk

### ISSUE THREAD

**Issue by kevin-montrose** [wesm/feather#300]
In my efforts to create a [.NET implementation of a Feather reader/writer](https://github.com/kevin-montrose/FeatherDotNet), I discovered that some column type values are never written to disk.

In particular

 - [CATEGORY](https://github.com/wesm/feather/blob/master/cpp/src/feather/metadata.fbs#L23) is serialized as an INT32
 - [DATE](https://github.com/wesm/feather/blob/master/cpp/src/feather/metadata.fbs#L26) also as an INT32
 - [TIMESTAMP](https://github.com/wesm/feather/blob/master/cpp/src/feather/metadata.fbs#L25) as an INT64
 - [TIME](https://github.com/wesm/feather/blob/master/cpp/src/feather/metadata.fbs#L27)  also as an INT64

In each case the "actual" type can be distinguished based on the column's associated metadata.

Is this behavior intended?  If so, it would probably make sense to remove CATEGORY, DATE, TIMESTAMP, and TIME from the [list of Types](https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/feather.fbs#L27) and document their expected underlying types (or are they allowed to vary?).

**Comment by wesm** [comment]
I strongly encourage you to direct your efforts toward implementing a .NET version of Apache Arrow. What you are describing is as intended, though.

**Comment by kevin-montrose** [comment]
Cool, follow up question:

Are the mappings in my original post guaranteed?

Stated another way - would it be legal for there to be a INT8 backed CATEGORY (or a SINGLE backed TIME)?  If so, what are the legal mappings?

Aside: Feather hits the sweet spot for my needs (passing results back and forth between R and C#).  Arrow is too large a project for me to tackle in the time I've got available (which is basically just the "write up"- time from attending NYR this year), though I do think it's a interesting project.

**Comment by wesm** [comment]
Right, but what I'm suggesting is that you could contribute your Feather C# implementation to Apache Arrow and leave it to other .NET developers to get involved and build out the implementation more completely. The distance between a functional Feather implementation and a working Arrow implementation is not as significant as it might seem (i.e. handling nested data and Arrow's slightly more general streaming and file formats).

**Comment by jreback** [comment]
cc https://github.com/ArvidJB

**Comment by wesm** [comment]
I ran into this problem when porting the Feather code into the Arrow repo. For the moment, until some R folks become more active in Arrow development, it's best to not make any changes to the Flatbuffers files

**Comment by wesm** [comment]
This is superseded by Feather V2 (coming in Arrow 0.17.0), which uses the Arrow IPC file format. Since we have an Arrow C# library now it might be most expedient to pursue this work there
