### ISSUE TITLE
Creating feather files from data stream with small memory footprint

### ISSUE THREAD

**Issue by schnorr** [wesm/feather#305]
Hello,

This is very similary to issue #272, but for writing feather files.

I am planning to use arrow's C++ API (installed in `arrow/ipc/api.h`) to create **feather** files so I can rapidly read them in R to ingest data in my tidyverse code. So, as of now, the only way to do it is to keep all columns in memory (using `arrow::DoubleBuilder->Append` for each column as objects in the data stream arrive) and at the end, when the stream finishes, call `feather_table->Append` with the name of each column and the corresponding in-memory array of values. The problem is that my input is a stream, and I want to avoid keep it all in memory. So, in a hypothetical ideal scenario, I'd create one table row at a time (eventually buffering multiple rows for performance reasons) and do a "row bind" operation in feather's TableWriter periodically. Such scenario, as far as I known, is impossible with the current arrow's feather C++ API since it let me manage only finished columns.

An `R` alternative would be to call `read_csv` (from the `readr` package) once the stream is finished, and them `write_feather` to get the appropriate feather files; but I want to avoid CSV files. Despite being slow on scale (> 100M lines with ~20 columns each), the costly parsing procedure creates a lot of temporary objects in memory.

What would be the best way, if possible, to do this with feather files? Thanks.

**Comment by wesm** [comment]
The Apache Arrow file and stream formats are designed for use in a memory constrained setting (see http://arrow.apache.org/docs/ipc.html and http://wesmckinney.com/blog/arrow-streaming-columnar/). I would be willing to evolve the Feather API to support chunked datasets and appends once there is an R-Arrow C++ binding, but until then we have a bit of a chicken and egg problem.

**Comment by wesm** [comment]
I recommend using the Arrow streaming format for this use case.
