### ISSUE TITLE
Native row subsetting on feather 

### ISSUE THREAD

**Issue by koustav-pal** [wesm/feather#306]
Hi,

I am currently developing a genomics R package for storage and retrieval of very large on disk matrices (dim(x) > 1M 1M) which is based on HDF, and I was wondering about trying out feather for doing much of the same things. The CRAN version of feather allows the reading of specific feather columns but it does not allow subsetting of both rows and columns. I understand this is a new format and it is still under development. Will row subsetting be available at a later time? @hadley

Alternatively, is the underlying c code capable of this functionality? only waiting on someone to create an R function for implementing it. Just curious.

**Comment by wesm** [comment]
Once we achieve more general R bindings for Arrow (and thus Feather), providing for row subsetting (aka predicate pushdown) isn't too far outside the realm of possibility. We need to find an invested party to help with the engineering work

**Comment by koustav-pal** [comment]
Hi wesm,

Sorry for digging up an old issue. I never got a chance to circumvent all my work to get back to this. 

Would it be possible for me to fork this and implement it on my own? Or is this something which you guys are planning on implementing in the near future?  

I have never touched C code before and I have generally always worked with R. So even if I tried to do this myself, I guess it would be a very slow process. 

I hope I'm not looking at a whale thinking it to be a fish.

**Comment by wesm** [comment]
There's some discussions on the Arrow mailing list about interfacing with R, it might make sense to continue discussing there: https://lists.apache.org/thread.html/90be64345ba44882757dd6aaaccf2b4f7522fbbff7cf849413428a4b@%3Cdev.arrow.apache.org%3E

**Comment by hadley** [comment]
I can't respond easily on that mailing list, but my team will probably take a look at feather bindings later in the year.

**Comment by wesm** [comment]
> I can't respond easily on that mailing list

What do you mean by this?

**Comment by hadley** [comment]
(Just that clicking reply didn't work for me - I'm sure I could sign up, but don't have time right this minute. Nothing major)

**Comment by wesm** [comment]
If you e-mail dev-subscribe@arrow.apache.org you'll be signed up and able to respond

**Comment by sachinruk** [comment]
Is row subsetting a feature now? My use case is to do something like `pd.read_feather('data.feather', where="serial number=='123456')`.

**Comment by wesm** [comment]
Not yet, but we are working to enable this logic in the Apache Arrow project

**Comment by wesm** [comment]
This is addressed by the new datasets API in the Arrow project, which is accessible via dplyr

**Comment by paulrougieux** [comment]
Links to the documentation:
- Use the python  `filter` keyword of the `dataset.to_table` method  https://arrow.apache.org/docs/python/dataset.html#filtering-data explains the
- Use the R dplyr `filter` function on the object returned by https://arrow.apache.org/docs/r/index.html
