### ISSUE TITLE
Are write_feather/read_feather atomic operation?

### ISSUE THREAD

**Issue by bluaze** [wesm/feather#307]
I use feather to cache long-running computation in R as it's extremely fast for writing/reading data.frames. When doing computation in parallel, is it necessary to add file lock before each write/read to avoid such situations as one process is writing a cached data.frame and another process could find the file and read in the uncompleted cache? In another words, are write_feather/read_feather atomic?

I have done some test. It seems working well without lock. And I have tried to dive into the underlying C++ code, but have found nothing as I have little knowledge on C++. So, could anyone give  an clear answer on this?

Thanks in advance.

**Comment by wesm** [comment]
No, they aren't atomic. So if another thread or process tries reading from an incomplete file, it will have an error

Once we start developing R bindings for Arrow, we can switch Feather to use a chunked format and we could develop some mechanism to enable incomplete files to be read as they are being written.
