### ISSUE TITLE
Platform is big endian. This is currently unsupported.

### ISSUE THREAD

**Issue by LogIN-** [wesm/feather#310]
When using non-standard `.First` function in .Rprofile installation of feather fails with following error:

**Issue:**

```
install.packages("feather")
Installing package into ‘~/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/feather_0.3.1.tar.gz'
Content type 'application/x-gzip' length 59616 bytes (58 KB)
==================================================
downloaded 58 KB

Welcome back xyz!
working directory is:xyz Mon Jul 24 13:30:01 2017

* installing *source* package ‘feather’ ...
** package ‘feather’ successfully unpacked and MD5 sums checked
Welcome back xyz!
working directory is:/tmp/RtmpHKgwVg/R.INSTALL3c497de13c17/feather Mon Jul 24 13:30:01 2017

Platform is big endian. This is currently unsupported.
ERROR: configuration failed for package ‘feather’
```

**Check in question:**
https://github.com/wesm/feather/blob/b4cc44de55aa0b72d7e216ff7f777a8155495bad/R/configure#L2

I was using specifically following custom `.First ` function, after removing it installation is successful as it should be in first place:

```
.First <- function() {
  message("Welcome back ", Sys.getenv("USER"),"!\n","working directory is:", getwd(), " ", date(), "\r\n")
}
```

**Comment by JackieMium** [comment]
Same problem here on Debian. Probably due to cumtom .First function too.

**Comment by wesm** [comment]
The repo isn't abandoned. Could someone submit a patch proposing a fix?

**Comment by wesm** [comment]
If this problem can be reproduced with the `arrow` package can you please open an issue with Arrow at http://issues.apache.org/jira?
