### ISSUE TITLE
Please make the documentation available via a web interface

### ISSUE THREAD

**Issue by napsternxg** [wesm/feather#312]
Are there a set of documentations and examples for using Feather in Python and R and other languages. 
It would be great if we can have either a readthedocs or a github.io website for feather with documentation of its various interfaces. 

Currently, I could only find the following webpage with a proper introduction to the features of Feather. 
https://blog.rstudio.com/2016/03/29/feather/

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-1307 -- the right place for this will by in the Python Arrow docs (since `import feather` is now just a thin wrapper around the `pyarrow.feather` module)

**Comment by GShotwell** [comment]
I just started using Feather and was going to write up some basic bits of the R interface. Would you all like a PR of some of this in the README?

**Comment by nealrichardson** [comment]
I'd be curious to see what you have, though it may ultimately make more sense as a vignette in [arrow](https://arrow.apache.org/docs/r/).

**Comment by wesm** [comment]
Yes, we aren't doing any more development in this repo, except to provide a migration path for people to use the `arrow` CRAN package

**Comment by nealrichardson** [comment]
`arrow` package docs are at https://arrow.apache.org/docs/r/

dev version of the docs are at https://ursalabs.org/arrow-r-nightly/
