### ISSUE TITLE
Check in a few sample datasets?

### ISSUE THREAD

**Issue by hadley** [wesm/feather#32]
That would make it easier to bootstrap new clients.

**Comment by kokes** [comment]
Yes! Also benchmarking could be then common across implementations.

And perhaps there could be equivalent CSVs (with some type information in the header, e.g. `colname (float64)`)? Or do you think the roundtrip tests are sufficient? I'm just thinking that the format may evolve and it would be helpful to have something human readable at hand. 

I still don't have feather on my Mac (issue already reported), so I could certainly use some reference data.

Thanks.

**Comment by wesm** [comment]
I think it would be best to add a data generation script for benchmarking purposes. We can also host sample feather files outside of the git repo.
