### ISSUE TITLE
[Python] feather.write fails with data from binary compressed SAS file read in from pandas.read_sas()

### ISSUE THREAD

**Issue by xiaodaigh** [wesm/feather#320]
I read in a binary compressed SAS dataset and I tried to write it out using to_feather() but it gives the following error 

> ValueError Traceback (most recent call last) in () 1 i = 1 2 for pdj in pdi: ----> 3 fr.write_dataframe(pdj, 'C:/test' + str(i) + '.feather') 4 i = i + 1 5
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyarrow\feather.py in write_feather(df, dest) 116 writer = FeatherWriter(dest) 117 try: --> 118 writer.write(df) 119 except: 120 # Try to make sure the resource is closed
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyarrow\feather.py in write(self, df) 94 95 elif inferred_type not in ['unicode', 'string']: ---> 96 raise ValueError(msg) 97 98 if not isinstance(name, six.string_types):
> 
> ValueError: cannot serialize column 0 named SOME_ID with dtype bytes

see https://stackoverflow.com/questions/46720520/how-to-read-binary-compressed-sas-files-in-chunks-using-panda-read-sas-and-save

I am using Windows 7 and Python 3.6. When I inspect it most the columns' cells are wrapped in `b'cell_value'`

**Comment by wesm** [comment]
Reported upstream as https://issues.apache.org/jira/browse/ARROW-1672
