### ISSUE TITLE
Reading in-memory within R session feather object in Python?

### ISSUE THREAD

**Issue by jeanvuda** [wesm/feather#327]
This is not an issue. I would like to know if this is possible?
Thank you for the wonderful work on this library. I have a scenario where I do some data pre-processing in R and do the rest in Python. But there is writing the file to the hard disk  step involved. I am wondering is there any possible way to read the in-memory R feather object (or in cache using memoise) in Python? This will remove the time writing it to hard disk and read them in python?

**Comment by wesm** [comment]
You could write to a ramdisk or something that's not a file, that would probably be the easiest thing that would work out of the box

**Comment by wesm** [comment]
This will be handled quite gracefully in the upcoming Arrow 0.17.0 release cc @nealrichardson
