### ISSUE TITLE
Feature request: Read and write dataset description in both R and Python

### ISSUE THREAD

**Issue by vnijs** [wesm/feather#328]
The R-help for `feather_metadata` states: "Returns the dimensions, field names, and types; and optional dataset description.". @hrbrmstr Kindly posted a [PR](https://github.com/wesm/feather/pull/326) to make this feature work and read and write a dataset description to a feather file from R. The dataset description could contain variable definitions, data source, etc., perhaps in markdown format.

It would be great if it were possible to read (and write) such a dataset description in python / pandas using feather.read_dataframe and feather.write_dataframe as well. I searched the documentation but couldn't find any information about this. It was hoping something like the following might work:

import feather
import pandas as pd
dat = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
dat._metadata = "# Test dataset\n\nThis dataset contains information on ..."
feather.write_dataframe(dat, "pydf.feather")

Or else perhaps:

feather.write_dataframe(dat, "pydf.feather", "# Test dataset\n\nThis dataset contains information on ...")

See also this [post on SO](https://stackoverflow.com/questions/47917549/read-and-write-a-dataset-description-as-a-pandas-dataframe-attribute)

**Comment by vnijs** [comment]
@shabbybanks did you try out @hrbrmstr 's PR (https://github.com/wesm/feather/pull/326)? That works fine in R but hasn't been merged into master (yet)

**Comment by wesm** [comment]
Sorry I never got to this. In the meantime, there is a new Feather V2 coming in Arrow 0.17.0, so if there is still interest in having file descriptions it would be straightforward to add them in the `arrow` library

**Comment by vnijs** [comment]
Thanks @wesm. I created an issue here: https://issues.apache.org/jira/browse/ARROW-8404

**Comment by vnijs** [comment]
Hi @wesm I created an issue in Jira in April 2020 with a request to add metadata to a (Pandas or R) data frame to store information about a dataset such as variable descriptions, data source, main data contact, changes, etc. etc. Pandas supports this option already but the only way to maintain this information is to use pickle to store the data which is not ideal.

On Jira it says _Priority > Major_ but it seems no one has been assigned to the issue. Is there any chance this feature gets added? If this is unlikely, I can close the issue. Thanks for your consideration and the fantastic work on arrow and pandas

https://issues.apache.org/jira/browse/ARROW-8404

**Comment by wesm** [comment]
We have so many issues, likely just no one has been able to volunteer to do the work. I think it's fine to leave it open and maybe someone will get to it someday

**Comment by vnijs** [comment]
Understood @wesm. Thanks for the reply. I'd be happy to contribute but don't have any experience with C++ which I assume is required here
