### ISSUE TITLE
[QUESTION] Feather 0.4.0 could be slower than Feather 0.3.1?

### ISSUE THREAD

**Issue by benitocm** [wesm/feather#329]
Hi,
Having the intention to move from Feather 0.3.1 to Feather 0.4.0, I did a quick test that consisted of reading a .csv compressed that contains around 33 millions of records where each record has 4 columns:
  ....
07300003030539,42198997,-1,2016-10-03T13:14:22.326Z
41130003053286,42224636,-1,2016-09-20T19:31:51.196Z
....
Once the file was read in a dataframe, a feather file was generated and read again as a feather file. The entire test is something like this:

df = pd.read_table(fn,sep=',',header=0)

%time feather.write_dataframe(df,'/var/tmp/df1.fth')
With feather 0.3.1
CPU times: user 2.32 s, sys: 3.16 s, total: 5.48 s
Wall time: 8.3 s

With feather 0.4.0
CPU times: user 8.81 s, sys: 3.06 s, total: 11.9 s
Wall time: 14.7 s

%time df = feather.read_dataframe('/var/tmp/df1.fth')
With feather 0.3.1
CPU times: user 3.22 s, sys: 2.13 s, total: 5.35 s
Wall time: 5.35 s

With feather 0.4.0
CPU times: user 4.43 s, sys: 3.4 s, total: 7.83 s
Wall time: 7.83 s

For installing feather 0.4.0, I needed to install pyarrow 0.8.0.

I know that this is just one example but I was expecting  the other way around, i.e., feather 0.4.0 + pyarrow 0.8.0 exceeds feather 0.3.1.

Is there an easy explanation for this result? Please, could you suggest another test where I can check that the upgrade from 0.3.1 to 0.4.0 is worth in terms of speed?

Thanks very much in advance.

**Comment by wesm** [comment]
It's possible there was a performance regression prior to the official release of pyarrow 0.8.0. I would like to investigate -- any chance you can make the CSV file you are using (or a sample of it) available?

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2059

**Comment by benitocm** [comment]
Hi,

I have rerun the tests without using notebook, the results are the following (time in milliseconds and the number of records is 30.075.594):


Testing with 0.3.1
Time taken to read .csv 58245
Time taken to write dataframe as feather 4313
Time taken to read dataframe as feather 5414

Testing with 0.4.0
Time taken to read .csv 58151
Time taken to write dataframe as feather 11770
Time taken to read dataframe as feather 4038

It seems that the problem is on the write operation.

I have also test with a bigger file (100 millions of records):

Testing with 0.3.1
Time taken to read .csv 180065
Time taken to write dataframe as feather 14323
Time taken to read dataframe as feather 20439

But the test with Feather 0.4.0 fails with this error:

  File "feather_test.py", line 41, in main
    feather.write_dataframe(df, fn2)
  File "/opt/alu/anaconda2/lib/python2.7/site-packages/pyarrow/feather.py", line 100, in write_feather
    writer.write(df)
  File "/opt/alu/anaconda2/lib/python2.7/site-packages/pyarrow/feather.py", line 80, in write
    batch = RecordBatch.from_pandas(df, preserve_index=False)
  File "pyarrow/table.pxi", line 705, in pyarrow.lib.RecordBatch.from_pandas (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:43576)
  File "pyarrow/table.pxi", line 739, in pyarrow.lib.RecordBatch.from_arrays (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:43825)
TypeError: Cannot convert pyarrow.lib.ChunkedArray to pyarrow.lib.Array

How many records do you need to investigate the problem?

Thanks

**Comment by wesm** [comment]
Even a million records would be helpful

**Comment by benitocm** [comment]
Here you are
[data.csv.gz](https://github.com/wesm/feather/files/1684483/data.csv.gz)

Apart from this, I found an exception using Feather 0.4.0 when handling a file not very large around 30M records when Feather 0.3.1  handles perfectly. Do you think that there could be more regression problems?

I also forget to tell you that Feather is super fast

Thanks

**Comment by wesm** [comment]
We're investigating in https://issues.apache.org/jira/browse/ARROW-2059, please follow along there. Thanks!
