### ISSUE TITLE
Date class from R -> Python -> R is not retained

### ISSUE THREAD

**Issue by DavisVaughan** [wesm/feather#330]
When writing a `tibble` with a `Date` column from `R -> feather -> Pandas -> feather -> R`, the `Date` class is lost and becomes `POSIXct`. 

I think this is happening when the python version of `feather` reads the file and converts it to a pandas DataFrame. It brings in the date column as `datetime64[ns]` which is then resaved as `datetime`, not `date`. But I am not sure if this is actually where the problem lies.

Using `reticulate` in R, here is a full reproducible example.

``` r
library(reticulate)
library(feather)
library(tibble)

PY_FEATHER <- import("feather")

tf <- tempfile(fileext = "feather")
tf2 <- tempfile(fileext = "feather")

ex <- tibble(date_col = as.Date("2018-01-01"))
ex
#> # A tibble: 1 x 1
#>   date_col  
#>   <date>    
#> 1 2018-01-01

feather::write_feather(ex, tf)

# No problem here
feather::read_feather(tf)
#> # A tibble: 1 x 1
#>   date_col  
#>   <date>    
#> 1 2018-01-01

# Metadata is "date". This is correct.
feather::feather_metadata(tf)
#> <Feather file>
#> [1 x 1] @ /var/folders/ln/vjgktwwx50jcvm7jq7jlnsbr0000gn/T//Rtmp3en49k/file13e6755c571eefeather
#> * 'date_col': date

# Now read into pandas
ex_pd <- PY_FEATHER$read_dataframe(tf)

ex_pd
#>     date_col
#> 0 2018-01-01

# And write it back using feather
PY_FEATHER$write_dataframe(ex_pd, tf2)

# Now read it back into R - Lost date, now reading as datetime
feather::read_feather(tf2)
#> # A tibble: 1 x 1
#>   date_col           
#>   <dttm>             
#> 1 2017-12-31 19:00:00

# The metadata is written incorrectly as datetime
feather::feather_metadata(tf2)
#> <Feather file>
#> [1 x 1] @ /var/folders/ln/vjgktwwx50jcvm7jq7jlnsbr0000gn/T//Rtmp3en49k/file13e6715baec40feather
#> * 'date_col': datetime
```

Created on 2018-02-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by xhochy** [comment]
This is a limitation of Pandas. It currently only support `datetime64[ns]` columns. There is not other native (read "fast") type available there for timestamps. Once you convert to Pandas, your data will end up as nanoseconds precision.

**Comment by DavisVaughan** [comment]
So even though I can "force" the conversion from `datetime64[ns]` to `datetime.date` on the Python side and then convert over correctly, that is not intended behavior? I would have imagined Pandas reading a column with `'date'` metadata and then consistently writing it back out to keep the `'date'` metadata rather than `'datetime'`, but if there are reasons for not wanting to use `datetime.date` in Pandas then I would understand that too. I don't know enough about that side of things. 

``` r
library(reticulate)
library(feather)
library(tibble)

PY_FEATHER <- import("feather")

tf <- tempfile(fileext = "feather")
tf2 <- tempfile(fileext = "feather")

ex <- tibble(date_col = as.Date("2018-01-01"))

feather::write_feather(ex, tf)

ex_pd <- PY_FEATHER$read_dataframe(tf)

# Force as datetime.date (object)
ex_pd$date_col <- ex_pd$date_col$dt$date
ex_pd
#>      date_col
#> 0  2018-01-01

ex_pd$dtypes
#> date_col    object
#> dtype: object

# And write it back using feather
PY_FEATHER$write_dataframe(ex_pd, tf2)

# Now read it back into R - Looks good now
feather::read_feather(tf2)
#> # A tibble: 1 x 1
#>   date_col  
#>   <date>    
#> 1 2018-01-01

# The metadata is correct
feather::feather_metadata(tf2)
#> <Feather file>
#> [1 x 1] @ /var/folders/ln/vjgktwwx50jcvm7jq7jlnsbr0000gn/T//Rtmpb8GWCj/file1750d1257eae7feather
#> * 'date_col': date
```

Created on 2018-02-16 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by xhochy** [comment]
There is sadly no way to consistently pass the metadata with a column that it is only representing date and not datetime in Pandas. The performance difference between a `datetime.date` and `datetime64` is really significant, on the order of many magnitudes. If you care about performance, you will always use the latter. Feather (and its underlying Apache Arrow format) has a DATE time but we chose to always convert that to `datetime64` during the Pandas conversion due to this performance difference.

**Comment by DavisVaughan** [comment]
That completely answered my question and was (sadly) what I expected. Thanks!
