### ISSUE TITLE
R NaN's in datetimes are transformed to -290308-12-21 19:59:06 after write and read

### ISSUE THREAD

**Issue by kinsvater** [wesm/feather#332]
Hi,

I am using the latest github version of the feather R package. Something strange happens if you write a table with an NaN into a datetime column:
df <- tibble(x = c(Sys.time(), NA, NaN))
print(df)
 A tibble: 3 x 1
  x                  
  \<dttm\>             
1 2018-03-07 11:39:29
2 NA                 
3 NA   

So far nothing special. But if instead you write and read this table in feather format, you will get the following:
feather::write_feather(df, "df.feather")
df2 <- feather::read_feather("df.feather")
print(df2)
 A tibble: 3 x 1
  x                  
  \<dttm\>             
1 2018-03-07 10:39:29
2 NA                 
3 -290308-12-21 19:59:06

In words: NaN's are saved as the datetime value -290308-12-21 19:59:06 but "ordinary" NA's are kept as NAs.

Best, Paul

**Comment by wesm** [comment]
If you can reproduce this with the `arrow::write_feather/read_feather` functions please let us know
