### ISSUE TITLE
Feather build error for R-3.5.0

### ISSUE THREAD

**Issue by vnijs** [wesm/feather#338]
FYI Only a source version is available for R 3.5.0 

![image](https://user-images.githubusercontent.com/2998956/39680763-1e507f1e-5159-11e8-85c6-9068504f67c1.png)

https://cran.r-project.org/web/checks/check_results_feather.html

**Comment by rvg02010** [comment]
This seems to be related to a dependency on `Rtools`, which is not yet available for 3.5.0. Hope this helps; don't know how to fix!

**Comment by vnijs** [comment]
@rvg02010 I was able to install from github in R 3.5 on Windows using `devtools::install_github("wesm/feather/R")` so I don't think `Rtools` is the issue.

**Comment by mtelesha** [comment]
I had to install RTools manually and add it to my path before it would work.

**Comment by mallick84** [comment]
I have also tried to install feather in R version 3.5, the following error is showing.

devtools::install_github("wesm/feather/R")

Downloading GitHub repo wesm/feather@master
from URL https://api.github.com/repos/wesm/feather/zipball/master
WARNING: Rtools 3.4 found on the path at C:/MANUAL~1/Rtools is not compatible with R 3.5.0.

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
Installation failed: Could not find build tools necessary to build feather

**Comment by mallick84** [comment]
@vnijs and @wesm : I have tried to install feather from devtools::install_github("wesm/feather/R").... after installing both the Rtool version i.e. Rtools 3.5 and 3.4 but nothing work. I am getting same error  as follows:

Downloading GitHub repo wesm/feather@master
 from URL https://api.github.com/repos/wesm/feather/zipball/master
 WARNING: Rtools 3.4 found on the path at C:/MANUAL~1/Rtools is not compatible with R 3.5.0.

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
 Installation failed: Could not find build tools necessary to build feather
Please any suggestion.

**Comment by eossiander** [comment]
@mallick84: I suggest uninstalling all your Rtools versions, then installing only Rtools 3.5. Then make sure it's in your path. 

This just worked for me.

**Comment by mallick84** [comment]
@eossiander , I have tried just as you said, but still the same error it is coming. just check the error.

Sys.getenv("PATH")


Sys.getenv("PATH")
[1] "C:\\Manually saved\\R-3.5.0\\library\\Cairo\\libs;C:\\Manually saved\\R-3.5.0\\bin\\x64;C:\\Manually saved\\Rtools\\bin;C:\\Manually saved\\Rtools\\gcc-4.6.3\\bin;C:\\Manually saved\\Rtools\\bin;C:\\Program Files\\ImageMagick-7.0.7-Q16;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\PC Connectivity Solution\\;C:\\PROGRAM FILES\\DELL\\DW WLAN CARD;C:\\PROGRAM FILES (X86)\\AMD APP\\BIN\\X86_64;C:\\PROGRAM FILES\\COMMON FILES\\MICROSOFT SHARED\\WINDOWS LIVE;C:\\PROGRAM FILES (X86)\\COMMON FILES\\MICROSOFT SHARED\\WINDOWS LIVE;C:\\PROGRAM FILES (X86)\\INTEL\\ICLS CLIENT\\;C:\\PROGRAM FILES\\INTEL\\ICLS CLIENT\\;C:\\Windows\\SYSTEM32;C:\\Windows;C:\\Windows\\SYSTEM32\\WBEM;C:\\Windows\\SYSTEM32\\WINDOWSPOWERSHELL\\V1.0\\;C:\\PROGRAM FILES (X86)\\WINDOWS LIVE\\SHARED;C:\\Program Files\\INTERNET EXPLORER;C:\\Program Files\\WIDCOMM\\Bluetooth Software\\;C:\\Program Files\\WIDCOMM\\Bluetooth Software\\syswow64;G:\\application\\bin\\win32;G:\\Softwere\\bin\\win32;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Manually saved;C:\\ProgramData\\Miniconda3;C:\\ProgramData\\Miniconda3\\Scripts;C:\\ProgramData\\Miniconda3\\Library\\bin"

See Rtools is in my path.

so while installing I get the same error.

devtools::install_github("wesm/feather/R")
Downloading GitHub repo wesm/feather@master
from URL https://api.github.com/repos/wesm/feather/zipball/master
WARNING: Rtools 3.5 found on the path at C:/MANUAL~1/Rtools is not compatible with R 3.5.0.

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
Installation failed: Could not find build tools necessary to build feather.

I have also tried in another way.

Just check it.

> library(devtools)
> Sys.setenv(PATH = paste("C:\\Manually saved\\Rtools\\bin", Sys.getenv("PATH"), sep = ";"))
> Sys.setenv(BRINPREF = "C:\\Manually saved\\Rtools\\mingw_32\\bin")
> devtools::install_github("wesm/feather/R")
Downloading GitHub repo wesm/feather@master
from URL https://api.github.com/repos/wesm/feather/zipball/master
WARNING: Rtools 3.5 found on the path at C:/MANUAL~1/Rtools is not compatible with R 3.5.0.

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
Installation failed: Could not find build tools necessary to build feather
> 

You see, I am getting same error. I do not know, what I am missing out.

**Comment by mtelesha** [comment]
I now can't install on my new Windows 10 even after manually installing RTools and putting it into the path.

**Comment by hadley** [comment]
Will be fixed as part of #367
