### ISSUE TITLE
Difference feather-format vs. pyarrow.feather

### ISSUE THREAD

**Issue by h-vetinari** [wesm/feather#341]
Currently, I'm importing `feather-format` through `import feather` (`pandas` does this for `.to_feather` as well as of v.0.23.1).

However, `pyarrow` seems much more up-to-date than this repo, and I've seen `from pyarrow.feather import feather` -- what are the differences (if any) between the two ways of importing feather, and what's the recommended library to use?

**Comment by wesm** [comment]
You can use either method; there is no explicit recommendation right now. `import feather` is provided for backwards compatibility

**Comment by h-vetinari** [comment]
Ok, thanks!
