### ISSUE TITLE
question: sparse support / plans?

### ISSUE THREAD

**Issue by amueller** [wesm/feather#344]
Hey.
So openml.org is looking (aka I'm trying to convince them) to move away from ARFF as the primary storage format.
I'm trying to understand the scope of feather better to see if it's a candidate.
Sorry if this has been answered elsewhere, I'm not trying to revive #188.

I saw that sparse dataframes are supported but I didn't find a lot of details. I assume because it's a columnar format there is some overhead involved for each column?

And interesting use-case is text data in bag-of-words format which is usually hundreds of thousands of features/columns. Would that be feasible or would you say that's out of scope / not a good fit?

Using feature-hashing can go even more extreme where there might be tens of millions of columns, some of them potentially completely empty.

Thanks!

**Comment by xhochy** [comment]
Please keep in mind that Feather is subset of the Arrow format. I will answer the questions with having full Arrow in mind, bust most likely already applies all to Feather. Therefore longer discussion and questions are better suited on the mailing list dev@arrow.apache.org (subscribe first at dev-subscribe@arrow.apache.org). I'm trying though to give you an answer for some of the questions here. If you consider pursuing this more, we should move this to the ML as there are more people that can answer these questions.

> I saw that sparse dataframes are supported but I didn't find a lot of details. I assume because it's a columnar format there is some overhead involved for each column?

Arrow itself does not support sparse data structures yet. Data is stored in RAM (and disk) in full dense arrays. There is support for memory-saving techniques like dictionary encoding but in that case, we still have at least a byte per row to indicate the dictionary value.

In contrast to this Parquet stores data using techniques like dictionary-, run-length- or delta-encoding. This should result in much less storage space on disk.

> And interesting use-case is text data in bag-of-words format which is usually hundreds of thousands of features/columns. Would that be feasible or would you say that's out of scope / not a good fit?

In the case of using a simple 2D table structures, this will result in 1bit per cell (row-in-a-column). With hundreds of thousands this could be very significant. Not sure how well this maps to the individual problems, it might be beneficial to actually store them as nested data. For example you could have a column of type `list<string>` or `list<struct<string, int>>`. This is supported by Arrow and Parquet alike.

> Using feature-hashing can go even more extreme where there might be tens of millions of columns, some of them potentially completely empty.

Millions of columns is something which we definitely are not support very good. Completely empty columns will neither use space for the actual data in Parquet or Arrow but the metadata definitely produces a significant amount of overhead.

**Comment by amueller** [comment]
thank you!

**Comment by wesm** [comment]
@amueller it would be helpful to have a complete listing of requirements for OpenML. It would be great if we could work together to establish a common open standard. The Arrow project is in the business of helping the community create and use standards for in-memory data (and on disk).

**Comment by amueller** [comment]
Sorry for the slow reply @wesm.
I'm not entirely sure I'm a good person to give the full list of requirements. @janvanrijn or @joaquinvanschoren might be better people to talk to.

From a consumer standpoint / scikit-learn standpoint, what I'd like to have is a format that can encode dense and sparse data with column names and per-column dtype, where the important dtypes for me are usually float, int and categorical (with named levels).
OpenML would possibly also like to encode the concept that a column is the target and/or that a column is an ID.

Happy to chat about this, I'm not sure if I'm answering your questions really.

**Comment by wesm** [comment]
Got it. I would like to see if Arrow could serve as the basis for a standard storage format. This likely means defining a suitable schema for encoding sparse data, or we might need to add something new to the standard.

**Comment by joaquinvanschoren** [comment]
Sorry for chiming in so late. We've recently started to look into this question more seriously. I think that @amueller sums up the requirements pretty well. Support for sparse data would be a major benefit for machine learning data, as Andreas explained.

Another obvious requirement for us are binding in the multiple languages we support (Python, R, Java, C#). There are also some third-party Go bindings. Possibly this is already covered by Arrow?

Meta-data such as special column types would be interesting but can probably also be attached separately. Does Feather have any means to store meta-data? Sorry for the newbie questions :).

**Comment by xhochy** [comment]
@joaquinvanschoren It would be better to move this to the Arrow mailing list (dev@arrow.apache.org, subscribe by mailing dev-subscribe@arrow.apache.org). I have the fear that discussions hear don't reach the full audience.

**Comment by wesm** [comment]
Agreed
