### ISSUE TITLE
Feather build error for R-3.5.1

### ISSUE THREAD

**Issue by AmrapalliKaran** [wesm/feather#346]
I am trying install a package "feather" in RStudio(Version 1.1.456) and base R(3.5.1), but keep getting error. I have used the command
"install.packages("https://cran.r-project.org/bin/windows/contrib/3.4/feather_0.3.1.zip", repos =NULL)" in RStudio display.
Even though the package got downloaded but while using library(feather), this error is been thrown..."Error: package or namespace load failed for ‘feather’:
 package ‘feather’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version".
I clearly understand that the package is not available for 3.5.1 version, hence is there any other alternative to this? If yes, then please do let me know. Thanks in advance.

**Comment by mtelesha** [comment]
I was able to install feather in 3.5.0 by manually installing RTools and put it into my environment. That no longer works.

**Comment by hadley** [comment]
Will be fixed as part of #367
