### ISSUE TITLE
Memory error when using  feather with tibble 1.4.99.9004

### ISSUE THREAD

**Issue by pablo14** [wesm/feather#347]
Reproducing the error:

```
devtools::install_github("tidyverse/tibble")
library(feather)
write_feather(mtcars, "mtcars.feather")
mtcars2 <- read_feather("mtcars.feather")
```

**Error: C stack usage  7970208 is too close to the limit**

Session info:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6


Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] feather_0.3.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.1     hms_0.4.2          tools_3.5.1        pillar_1.3.0.9000  rstudioapi_0.7     yaml_2.1.19       
 [7] tibble_1.4.99.9004 crayon_1.3.4       Rcpp_0.12.18       pkgconfig_2.0.2    rlang_0.2.2 
```

It also throws other error on a linux server (same case):
`Error: evaluation nested too deeply: infinite recursion / options(expressions=)?`

The solution: using the last version on CRAN. 
Thanks!

**Comment by huftis** [comment]
I too got a similar problem. But it seems to be fixed by commit #353 (not yet on CRAN).

**Comment by karldw** [comment]
It's also worth mentioning that this is more of an issue now than when @pablo14 mentioned it because the CRAN version of tibble (2.0.0) now raises this error when running `read_feather`.

**Comment by hadley** [comment]
Will be fixed as part of #367

**Comment by burado88** [comment]
Just wondering, when would the new version be available on CRAN? Is there any workaround? My R crashes as soon as I try to load a feather file.

**Comment by karldw** [comment]
@burado88, looks like it's currently available!
https://cran.r-project.org/web/packages/feather/
