### ISSUE TITLE
Segmentation fault when loading feather with category type.

### ISSUE THREAD

**Issue by minimumnz** [wesm/feather#348]
Code that worked with previous version of pandas seems to Segfault with categorical types.

```import pandas as pd
import feather

df = pd.DataFrame(['sally jones', 'michael jones'], columns=['name'])
df['name'] = df['name'].astype('category')
feather.write_dataframe(df, f'name.feather')

df = feather.read_dataframe(f'name.feather')
```

![image](https://user-images.githubusercontent.com/1134580/45934986-d7052280-bff9-11e8-8315-4b4a90c310d0.png)

**Comment by wesm** [comment]
I can't reproduce here. What version of `pyarrow` do you have installed?

**Comment by minimumnz** [comment]
'0.8.0'

I upgraded this to 0.10.0 and it fixed the problem. Thanks
