### ISSUE TITLE
pyarrow.lib.ArrowTypeError:  "Expected a string or bytes object, got a 'int' object"

### ISSUE THREAD

**Issue by clayms** [wesm/feather#349]
could in-place type coercion or promotion be applied with a warning to prevent this?

```py
import pandas as pd

testdf = pd.DataFrame({'testcol':['item1', 'item2', 3, 'item4']})

testdf.to_feather('testdf.feather')

```

end of Traceback
```py
 File "pyarrow/array.pxi", line 182, in pyarrow.lib.array
 File "pyarrow/array.pxi", line 82, in pyarrow.lib._ndarray_to_array
 File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected a string or bytes object, got a 'int' object", 'Conversion failed for column testcol with type object')

```

Simple work-around:

```py
import pandas as pd

testdf = pd.DataFrame({'testcol':['item1', 'item2', 3, 'item4']})
testdf['testcol'] = testdf['testcol'].astype(str)

testdf.to_feather('testdf.feather')
```

**Comment by xhochy** [comment]
This is the same issue as https://github.com/pandas-dev/pandas/issues/21228 For the moment we don't plan to do any coercion. This must be done explicitly by the user. Thus the error is valid and indicates wrongly typed data.

**Comment by chandrabhushanroy** [comment]
The following lines seem to solve this problem.
STEP-1: Convert the pandas dataframe into pyarrow table with following line of code.
`table = pa.Table.from_pandas(df_image_0)`

STEP-2: Now, write the data in paraquet format.
`pq.write_table(table, 'file_name.paraquet')`

**Comment by sidoroffmichael** [comment]
I get the same error too.
My question is @xhochy - 

1. Why would it be reasonable, from your perspective, to demand to change the **dtype** of the columns? Don't you think that the columns are of this particular type for a good reason? 

2. Is there any way to fix this issue without needing to change the **dtype**?

Thanks

**Comment by y-da-zhuang** [comment]
> 我也遇到了同样的错误。 我的问题是@xhochy-
> 
> 1. 从您的这些角度来看，为什么要求更改列的**类型**是合理的？
> 2. 有什么方法可以在此不需要更改问题**类型**的情况下的解决方案？
> 
> 谢谢

I also encountered the same problem, how did you solve it?

**Comment by dendihandian** [comment]
I got this error too while using wr.to_parquet() in awswrangler. I can't debug what's wrong in it.

```
File "pyarrow/array.pxi", line 323, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected bytes, got a 'int' object
```

**Comment by TJMac93** [comment]
This error has started appearing for me over a year into a program that is run daily and has not changed, nor have any libraries been updated. 

> "Expected bytes, got a 'int' object"

Why is this happening? I don't understand why the engine is expecting a certain dtype at all. Every row in the column is an int, and I have not specified a schema when saving, so why is it expecting bytes?
