### ISSUE TITLE
how to delete a feather file (whose creation has been aborted)?

### ISSUE THREAD

**Issue by randomgambit** [wesm/feather#350]
Hello there,

Thanks for this amazing format. I really like the interoperability between Python and R. 

I wonder if the following is a bug. When I create a large file with `pandas` and I write to disk using `to_feather`, then killing the processing makes me UNABLE to delete the file from my folder.

Windows complains that the file is still in use in `python` (although the processing has stopped permanently). This is annoying because it seems I must restart my session to "break" the link with Python.

Am I missing something here?
Thanks!

**Comment by wesm** [comment]
I'm not sure; Windows can be quite difficult about these things. If writing a Feather file fails for some known reason (e.g. an exception is raised), then the code will delete the file. If the process is killed while the file is being written, then I'm not sure. It's not really a Feather-specific issue

**Comment by randomgambit** [comment]
I see, thanks. however this only happens with `feather`. killing a csv or a parquet writing allows me to remove the file afterwards...

**Comment by wesm** [comment]
I see. I am unlikely to have time to look into this, but recommend you open an issue on the Apache Arrow JIRA. I'm not sure what would need to change

**Comment by wesm** [comment]
I think this is addressed by the `arrow` Feather functions now. Closing
