### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ctberthiaume** [wesm/feather#352]
This project looks very promising, but there haven't been commits in over a year and there's no documentation. Are there still plans to continue development? Or has development stalled because there's some other fast language agnostic data frame exchange project that has filled the need that justified feather?

**Comment by wesm** [comment]
This is my least favorite kind of GitHub issue. 

> some other fast language agnostic data frame exchange project 

That's Apache Arrow, which is what Feather uses. Read: http://wesmckinney.com/blog/feather-arrow-future/

We are working on getting R bindings for Arrow up and running, and then `library(feather)` will depend on `library(arrow)`. Hard to say for timeline, 6 months maybe
