### ISSUE TITLE
installing feather R from github with devtools  gives fatal error

### ISSUE THREAD

**Issue by zalazhar** [wesm/feather#356]
Installing feather R from github with devtools as provided in the documentation (devtools::install_github("wesm/feather/R") gives the following error below.: 

It seems to be that it can't find feather/api.h

In file included from RcppExports.cpp:4:0:
feather_types.h:2:10: fatal error: feather/api.h: No such file or directory
 #**include "feather/api.h"**
          ^~~~~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘feather’
* removing ‘/home/zakkie/R/x86_64-pc-linux-gnu-library/3.4/feather’
* restoring previous ‘/home/zakkie/R/x86_64-pc-linux-gnu-library/3.4/feather’
Installation failed: Command failed (1)

**Comment by hadley** [comment]
This worked for me; there have been a few fixes lately so I suspect we fixed the root cause.

**Comment by hadley** [comment]
Hmmm strange. You might try asking on <https://community.rstudio.com>

**Comment by zalazhar** [comment]
Many thanks Hadley. Will do that.
