### ISSUE TITLE
R Feather Cran Version gives IO error when writing and Reading

### ISSUE THREAD

**Issue by zalazhar** [wesm/feather#357]
Installed feather on R 3.4.4 via CRAN, but the package gives an error when writing and reading feather files. It generates the follwoing error:   

- feather::write_feather(klm[[1]], path = getwd())

Error in writeFeather(x, path) : 
  IO error: Failed to open file: /home/zakkie/Mortality

Similarly when reading feather files.

**Comment by wesm** [comment]
Need to provide a file path, not a directory
