### ISSUE TITLE
Adapted Feather to caching with concise interface. Opinions?

### ISSUE THREAD

**Issue by kiwi0fruit** [wesm/feather#360]
[Feather Helper](https://github.com/kiwi0fruit/pandoctools/tree/master/pandoctools/feather). What do you think?

**Comment by wesm** [comment]
Looks interesting. I'm not sure how it's relevant to this project though, since we're just reading and writing the files?

**Comment by kiwi0fruit** [comment]
I thought Feather is all about fast reading and writing files (and cross-language too)? Is it something more?

**Comment by kiwi0fruit** [comment]
I see. Thanks :)

>
