### ISSUE TITLE
ArrowNotImplementedError: halffloat

### ISSUE THREAD

**Issue by sayakpaul** [wesm/feather#362]
Following are the `dtypes` of the Pandas Dataframe I am using:

![image](https://user-images.githubusercontent.com/22957388/50009866-0d8d8080-ffde-11e8-96b7-bb838bc2680a.png)

My Python code:
```python
df_raw.to_feather('malware-raw')
```

Error stack:
![image](https://user-images.githubusercontent.com/22957388/50009964-4594c380-ffde-11e8-84e4-9f259db4c569.png)

Need help in resolving this!

**Comment by wesm** [comment]
Float16 is not implemented in the Feather format yet. Please open a JIRA issue about this

**Comment by wesm** [comment]
Feather V2 (coming in pyarrow 0.17.0) supports half floats
