### ISSUE TITLE
pyarrow.lib.ArrowNotImplementedError: list<item: string>

### ISSUE THREAD

**Issue by fahadshery** [wesm/feather#363]
Hi, I am using python for NLP and feather to exchange dataframes between R and python. Here is the re-produceable example:

`import pandas as pd`
`from textblob import TextBlob`
`import feather`

`data = {'tweet':['Analytics Fahad provides a great platform to learn data science', 'Good service', 'no communication from you', 'terrible experience','Waiting callback to ask how things are'],'doc_id':[28,34,29,42,44]}`

`df = pd.DataFrame(data)`
`#df['sentiment'] = df['tweet'].apply(lambda tweet: TextBlob(tweet).sentiment)
df['nouns_p'] = df['tweet'].apply(lambda tweet: TextBlob(tweet).noun_phrases)
print(df)`
`path = 'example_noun_phrases.feather'`
`feather.write_dataframe(df, path)`

Here is the error:

`Traceback (most recent call last):
  File "C:\Users\607518~1\AppData\Local\Temp\RtmpKWZDDp\chunk-code-6598338e3ba7.txt", line 13, in <module>
    feather.write_dataframe(df, path)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\pyarrow\feather.py", line 178, in write_feather
    writer.write(df)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\pyarrow\feather.py", line 94, in write
    self.writer.write_array(name, col)
  File "pyarrow\feather.pxi", line 67, in pyarrow.lib.FeatherWriter.write_array
  File "pyarrow\error.pxi", line 89, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: list<item: string>`

As a result I can't read the feather back in to R for further analysis. I have also commented a line which gives sentiment score. This causes a bigger error msg. you can try that yourself.

I am an R user with basic python3 understanding. Any pointers will be appreciated

Regards,

**Comment by wesm** [comment]
Nested types aren't supported in the Feather format right now

**Comment by philipsd6** [comment]
> Nested types aren't supported in the Feather format right now

or ever? (speaking from 10 months later...)

**Comment by wesm** [comment]
See "Feather V2" discussion

https://issues.apache.org/jira/browse/ARROW-5510

We are a volunteer-based community so things happen based on people being willing to do the work.

**Comment by eyast** [comment]
How can i help facilitate this feature becoming reality? I am wondering if funding is something that could help. I hope I am not sounding arrogant, i simply want to ask if that's a problem money can solve - and if so where can i domate/pay for your hard work. thx

**Comment by wesm** [comment]
You can easily sponsor us at https://github.com/sponsors/ursa-labs

**Comment by wesm** [comment]
Feather V2 (coming in Arrow 0.17.0) supports nested data

**Comment by rubzk** [comment]
Hello, I am getting the same error trying to convert nested data to feather.

Making a pip freeze  I have

arrow==0.17.0
pyarrow==2.0.0

To my concern both versions already supports Feather v2 rigth?

**Comment by wesm** [comment]
Can you report an error in Apache Arrow and provide a reproducible example of the error?
