### ISSUE TITLE
Hoping to save a tibble of columns of type "labeled" with feather.

### ISSUE THREAD

**Issue by AHoerner** [wesm/feather#366]
I am attempting to save the output of the ipumsr package as applied to the Current Population Survey as a feather file. Almost all of the feather output is of type "labeled," in a format I understand to be identical to that produced by the haven package.

feather seems to strip off the labels, or at least, I do not see them. If they are there, is there a way to make them visible? if they are not there, is there any way for me to get them there?

Hope so, because Man! these feather files are like lightning.

**Comment by wesm** [comment]
Since we're migrating feather for R to https://github.com/apache/arrow this is probably something we could tackle there. Note that the performance will be even better once `library(feather)` is running atop the `library(arrow)` package

cc @romainfrancois

**Comment by wesm** [comment]
It seems like we should be able to serialize all the attributes now, but I'm not sure what the status is. @nealrichardson do you know?

**Comment by nealrichardson** [comment]
We have a ticket for this: https://issues.apache.org/jira/browse/ARROW-4390

Let's continue discussion there.
