### ISSUE TITLE
feather_metadata seems broken  in R

### ISSUE THREAD

**Issue by vnijs** [wesm/feather#368]
It seems that `feather_metadata` has some IO issues in the new release of feather on CRAN (0.3.2). See example below.

@jimhester_ Related to this, any chance of getting @hrbrmstr's [PR](https://github.com/wesm/feather/pull/326) into the next release?

```
library(feather)
dat <- data.frame(a = 1:3, b = 4:6)
attr(dat, "description") <- "A data.frame with the following information: ..."
write_feather(dat,  path = "~/df.feather")
rdat <- read_feather("~/df.feather")
feather_metadata("~/df.feather")

Error in metadataFeather(path) : 
  IO error: Failed to open file: ~/df.feather
```

**Comment by s-aibar** [comment]
Hi, 

It seems this issue happens in `feather::feather_metadata()`when including `~` in the path (the function `feather::read_feather` works fine). 

(It could easily be solved using `path.expand()` or something similar...)

**Comment by wesm** [comment]
The `feather_metadata` function is deprecated
