### ISSUE TITLE
Python README.md is not rendering correctly on PyPI

### ISSUE THREAD

**Issue by alchemyst** [wesm/feather#369]
The headings and source code parts are not rendering correctly on PyPI

![image](https://user-images.githubusercontent.com/236588/51583580-f47bc780-1ed9-11e9-8b2f-0210e8bfb16a.png)

**Comment by wesm** [comment]
PRs welcome

**Comment by jameslamb** [comment]
@wesm could this issue be closed?

@alchemyst in the future, consider adding "(fixes #some_number)" to the title of your PR and / or the end of your commit message. If you do that, then GitHub will close the corresponding issue automatically when your PR is merged!

**Comment by alchemyst** [comment]
@jameslamb [I did that](https://github.com/wesm/feather/pull/370). I'm not sure why GitHub didn't pick it up. 

Perhaps we can keep the issue open until @wesm uploads a new release to PyPI and we have confirmed the rendering is correct?
