### ISSUE TITLE
Remove .NOTPARALLEL

### ISSUE THREAD

**Issue by hadley** [wesm/feather#373]
From CRAN:

> .NOTPARALLEL is a GNUism, and these packages do not declare GNU make -- 
> there are other parallel makes available on R platforms where it will 
> not work as intended if it is actually needed.  As 'Writing R 
> Extensions' has warned for quite a while now ....
> 
> For feather, AFAICS the Makefile is one of many unused files.

**Comment by hadley** [comment]
cc @jimhester can we remove this?

**Comment by jimhester** [comment]
Looks like we could `.Rbuildignore` the Makefile entirely, the R package is not using it.

**Comment by hadley** [comment]
Do you have time to make that change and do a quick release? It's currently causing [WARNING](https://cran.r-project.org/web/checks/check_results_feather.html)s
