### ISSUE TITLE
Incompatibility with tibble>=2.0.0

### ISSUE THREAD

**Issue by alexmac** [wesm/feather#374]
After upgrading to tibble 2.0.1 for another library read_feather is giving this error:

```Error: evaluation nested too deeply: infinite recursion / options(expressions=)?```

Has anyone seen this before? do we just need to recompile feather or is it not compatible with this new version?

**Comment by scworland-usgs** [comment]
I am having the same issue

**Comment by jameslamb** [comment]
@scworland-usgs @alexmac I observed this too in many projects I work on. I believe that the breaking changes in `tibble` 2.0.0 are why the maintainers came back here to release `feather` 0.3.2. Could you try upgrading to `feather` 0.3.2 and see if it solves the problem? It did for me!

@hadley @hadley I think this issue can be closed.

**Comment by hadley** [comment]
Thanks @jameslamb — we should probably do a minor release of feather than encodes this dependency in the DESCRIPTION so that tibble gets automatically updated.

**Comment by jameslamb** [comment]
@hadley is #375 the right place to add the version floor? Or do you want to do a minor release before dealing with that PR?
