### ISSUE TITLE
Read file in "feather" format by command "View"

### ISSUE THREAD

**Issue by andirey** [wesm/feather#377]
There is a command "View" in R Studio that allows read data file, for example, by clicking it in the "Files" tab. It will be very cool to have the same command or plug-in for R Studio to read files in "feather" format.

**Comment by wesm** [comment]
Do you want to request this in the RStudio IDE?

**Comment by andirey** [comment]
Yes, thank you. I did it
https://community.rstudio.com/t/read-file-in-feather-format-by-command-view/37114
Hope it will be useful.
