### ISSUE TITLE
Reading/writing fails for large data.frames

### ISSUE THREAD

**Issue by traversc** [wesm/feather#380]
I'm trying to use feather to transfer large data.frames between R and Python.  

However, reading data fails after some size.  Below is a brief reproducible example:

```
seqs <- paste0(rep("A", 77), collapse="")
N <- 40000000 # 40 million
df <- data.frame(sequences = seqs, var1 = runif(N), var2 = sample(N), stringsAsFactors = F)
write_feather(df, path = "/tmp/test.feather")
z <- read_feather("/tmp/test.feather")
```

I am using the latest CRAN version.

**Comment by nealrichardson** [comment]
Could you characterize the failure in some way?

Also, have you tried with the `arrow` package? It has a more [robust and performant implementation](https://arrow.apache.org/blog/2019/08/08/r-package-on-cran/) of `read/write_feather`

**Comment by traversc** [comment]
Here's the error I get using `read_feather`.  

```
Error in coldataFeather(x, i) : 
  embedded nul in string: '\0\0`\x9a2\x82\xe3?\0\0\0p&Q\xe4?\0\0\xc0ѵ\x8c\xe2?\0\0\x80\xed\xf7A\xe2?\0\0\x80ALS\xdd?\0\0\0\xfa=\x9e\xc3?\0\0\xe0U\017\xe0\xe0?\0\0\0\xc3Ń\xcf?\0\0\xa0\x85M \xe4?\0\0\05\xe7'
```

**Comment by traversc** [comment]
Thanks for pointing towards the `arrow` package.  It seems faster, but it also gives an error:


```
library(arrow)

seqs <- paste0(rep("A", 77), collapse="")
N <- 40000000 # 40 million
df <- data.frame(sequences = seqs, var1 = runif(N), var2 = sample(N), stringsAsFactors = F)
arrow::write_feather(df, stream = "/tmp/test.feather")
z <- arrow::read_feather("/tmp/test.feather")
```

```
Error in Table__to_dataframe(x, use_threads = option_use_threads()) : 
  Invalid: Invalid offset buffer
```

Should I open an issue on the arrow package?

**Comment by nealrichardson** [comment]
Well, failing faster is an improvement I guess ;)

It sounds like you may be hitting https://issues.apache.org/jira/browse/ARROW-3317. Until that's resolved, if you can chunk your data frame into multiple parquet files, you can read them with `pyarrow` as a single unit with the `ParquetDataset` class: https://arrow.apache.org/docs/python/parquet.html#reading-from-partitioned-datasets

Similar functionality is coming soon to the `arrow` R package.

**Comment by wesm** [comment]
This should be fixed in the `arrow::write_feather/read_feather` functions
