### ISSUE TITLE
"cannot serialize duplicate column names"

### ISSUE THREAD

**Issue by jytan89** [wesm/feather#382]
I am working on a dataframe that is actually a cosine-similarity DataFrame. Hence, the column names and row names are mirror images of each other (kind of like a correlation heatmap).

I get the error as above in the title when I am trying to save the dataframe:
```
"ValueError: cannot serialize duplicate column names"
```
Can someone help me with this? Technically I don't have any duplicated column names, but the row names and column names are the same.

Thanks in advance!

**Comment by wesm** [comment]
Did you have some resolution?

**Comment by jytan89** [comment]
> Did you have some resolution?

Hi there, yes I have resolved this. Thank you for asking!
