### ISSUE TITLE
Should feather::read_feather respect options(stringsAsFactors = FALSE)?

### ISSUE THREAD

**Issue by khughitt** [wesm/feather#384]
Greetings!

Is there any reason why the R implementation of `read_feather()` ignores the state of the `stringsAsFactors` option?

For consistency, it seems like it would be useful to have it behave in a similar manner to `read.delim()`, `read_tsv()`, etc...

Ex:

```r
library(feather)
library(tidyverse)
options(stringsAsFactors = FALSE)

write_tsv(head(iris), 'test.tsv')
write_feather(head(iris), 'test.feather')

head(read.delim('test.tsv', sep='\t')$Species)
# [1] "setosa" "setosa" "setosa" "setosa" "setosa" "setosa"

head(read_tsv('test.tsv', col_types = cols())$Species)
# [1] "setosa" "setosa" "setosa" "setosa" "setosa" "setosa"

head(read_feather('test.feather')$Species)
# [1] setosa setosa setosa setosa setosa setosa
# Levels: setosa versicolor virginica
```

Incidentally, I checked `read_parquet()` and it too ignores `stringAsFactors`.

**Versions**:

- R 3.6.2
- feather 0.3.5

**Comment by wesm** [comment]
Can you open an issue on the Arrow JIRA issue tracker?

**Comment by khughitt** [comment]
Sure thing - reported issue here: https://issues.apache.org/jira/browse/ARROW-7823

I created a similar issue for `read_parquet()` as well.

**Comment by nealrichardson** [comment]
Thanks!
