### ISSUE TITLE
python feather-format 0.4.0 is incompatible with pyarrow 0.17.0: ImportError FeatherError FeatherReader FeatherWriter

### ISSUE THREAD

**Issue by joseortiz3** [wesm/feather#387]
Installed `feather-format` and `pyarrow` in python 3.8.2 today, ran into this problem resulting in an `ImportError`.

The `feather` script `api.py` tries to import:

```python
from pyarrow.feather import (read_feather as read_dataframe,  # noqa
                             write_feather as write_dataframe,
                             FeatherError,
                             FeatherReader,
                             FeatherWriter)
```
But in pyarrow 0.17.0, `FeatherError` and `FeatherReader` have moved to `pyarrow.lib`. I don't know where `FeatherWriter` went, I couldn't find it.

So, I uninstalled `pyarrow` and `python -m pip install pyarrow==0.16.0` instead, fixed the problem.

Just a heads up that people will start running into this problem.

**Comment by wesm** [comment]
Thanks, will fix. Didn't know people were still directly relying on `feather-format` (most people go through pandas)

**Comment by joseortiz3** [comment]
Oh whoops, you're right. I'm not sure if people are relying on it, turns out I'm using pandas instead. Thanks!

**Comment by wesm** [comment]
Fixed in https://github.com/wesm/feather/commit/1fb72bcd1fa89f24cd185b13b661060c48683417 and pushed to PyPI as feather-format==0.4.1
