### ISSUE TITLE
[feature request] support for complex numbers

### ISSUE THREAD

**Issue by baptiste** [wesm/feather#59]
R data frames support complex numbers, but feather apparently does not.

**Comment by hadley** [comment]
@wesm this seems like it should be straightforward - a compound data type with real and imaginary double primitive arrays.

**Comment by wesm** [comment]
What is the memory layout of complex numbers in R? In Python, we generally use `complex64` or `complex128`, which are packed struct types (two floats or two doubles). But the real and imaginary parts for each value are next to each other in memory.

**Comment by hadley** [comment]
Oh good point - I'd never actually worked with complex numbers in R before. They're also packed structs (only doubles).

**Comment by baptiste** [comment]
[side-note] it's funny, Dirk keeps reminding me that I'm the only known user of complex numbers in Rcpp; egoistically I keep requesting "i" everywhere ;) 
Why do we need more imaginary numbers in the physical world than in statistics? Even my [Faddeeva package](https://cran.r-project.org/web/packages/RcppFaddeeva/index.html), which sounds very statisticsy, originated from a physics problem.

**Comment by ScottPJones** [comment]
They do seem to be used frequently enough in Julia, for whatever reason, and support any type `<: Real` for the real and imaginary parts, `Complex64` and `Complex128` having type aliases, as they are the most used, of course. I think it would be very important to keep the parts next to each other.

**Comment by wesm** [comment]
This seems like a straightforward patch for someone with C++ appetite (and perhaps also Python to test with complex64/complex128) to take on. I will have little bandwidth (except perhaps to create a C API) until May.

**Comment by wesm** [comment]
It would be straightforward to add complex numbers to Feather; if there is interest, can you open a JIRA in Apache Arrow? Thanks
