### ISSUE TITLE
[feature request] support for nested data

### ISSUE THREAD

**Issue by dselivanov** [wesm/feather#62]
Would be great to add support for complex columns - i.e. lists of arbitrary data.

``` r
df <- data.frame(i = 1:10)
df$i_lst <- lapply(1:10, function(x) letters[1:3])
str(df)
```

> 'data.frame': 10 obs. of  2 variables:
>  $ i    : int  1 2 3 4 5 6 7 8 9 10
>  $ i_lst:List of 10
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"
>   ..$ : chr  "a" "b" "c"

``` r
write_feather(dt, '~/test.feather')
```

> Error: Not implemented: i_lst is a list

**Comment by kendonB** [comment]
+1

**Comment by giu87** [comment]
+1

**Comment by obrl-soil** [comment]
+1. with simplefeatures, this could finally be a viable alternative to shapefile.

**Comment by wesm** [comment]
Nested data supported in Feather V2 (in the upcoming `arrow` 0.17.0 package)
