### ISSUE TITLE
Deploying feather in shinyapps.io

### ISSUE THREAD

**Issue by mosscoder** [wesm/feather#67]
Greetings, I would like to make use of this package with a shiny app deployment on shinyapps.io. 

I receive the following error at deployment:

ERROR: compilation failed for package ‘feather’
* removing ‘/usr/local/lib/R/site-library/feather’
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 176565252 failed: Error building image: Error building feather (0.0.0.9000). Build exited with non-zero status: 1
Execution halted

Can anyone advise on how I might deploy with feather?

**Comment by jjallaire** [comment]
@kevinushey Is this an issue with packrat and handling GitHub packages that are hosted in a sub-directory of a repo rather than the root?

**Comment by kevinushey** [comment]
That seems like the most likely explanation -- I think `packrat` does the equivalent of 'download zipped contents of branch' and then `R CMD INSTALL` on that zipfile, which won't succeed in cases like this.

**Comment by hadley** [comment]
I think feather + shinyapps will probably need to wait for a CRAN release
