### ISSUE TITLE
Feature request: support  R connections instead of just files

### ISSUE THREAD

**Issue by bwlewis** [wesm/feather#69]
Someday, would be cool if connections were supported too.

This project is beautiful, by the way!

**Comment by hadley** [comment]
We should do that post 3.3 so we can use the new connections API!

**Comment by bwlewis** [comment]
The format appends metadata at the end, and code frequently looks to the end of the file (see https://github.com/wesm/feather/blob/master/doc/FORMAT.md). This might be a problem for a connections interfance.

**Comment by wesm** [comment]
If this is still of interest, can you open an issue in Apache Arrow? cc @nealrichardson
