### ISSUE TITLE
Windows build fails due to missing sys/mann.h

### ISSUE THREAD

**Issue by aadler** [wesm/feather#71]
I am trying to build feather on Windows7 64bit using R-patched (3.2.4) and Rtools 3.3.0 V1959 (as discussed in https://github.com/wesm/feather/issues/58). I sort-of followed @wesm's advice by cloning the repository and manually taking the actions in the [R/configure](https://github.com/wesm/feather/blob/master/R/configure). The build proceeds until [io.cc](https://github.com/wesm/feather/blob/master/cpp/src/feather/io.cc) whereupon it fails as Windows installations of gcc do not have sys/mann.h

The older answers (like in SO) which directed one to https://code.google.com/archive/p/mman-win32/ are not useful as that is a dead link now. Can anything be done to get around this?

Thank you.

**Comment by edwindj** [comment]
@eddelbuettel used it for making rcppannoy windows compatible: https://github.com/eddelbuettel/rcppannoy/blob/master/inst/include/mman.h . It seems that you can mimic/copy that approach. (I don't know the limitations of the mman-win32 port).

**Comment by eddelbuettel** [comment]
Wasn't me but @thirdwing who contributed that to my repo.  AFAIK standard windows trick to get it closer to what real POSIX systems have in that regard.

**Comment by wesm** [comment]
I'm only using memory-mapping on POSIX systems as a convenience and to avoid temporary allocations. Feel free to submit a patch that disables `sys/mman.h` on Windows compilers and opt for the non-memory-mapped data source

**Comment by eddelbuettel** [comment]
Should be doable as RcppAnnoy and the underlying Annoy library demonstrate.  (And they are indeed a nice blue print for clean C++ used by Python and then R(cpp) bindings.)   I don't care all that much about Windows myself so would be @aadler or another contributor for the patch though.

**Comment by aadler** [comment]
@thirdwing built a patch, and it compiles, but I'm getting downstream errors. I guess we should handle that in the pull request discussion: https://github.com/wesm/feather/pull/75 and possible close this issue?

Thanks.

**Comment by aadler** [comment]
Got it to work. WOW is it fast!

```
> library(nycflights13)
> microbenchmark(saveRDS(flights, './inst/feather/mt.rds'), write_feather(flights, './inst/feather/mt.feather'), times = 10L, control = list(order = 'block'), unit = 'relative')
Unit: relative
                                                expr      min       lq     mean   median       uq     max neval cld
           saveRDS(flights, "./inst/feather/mt.rds") 35.24434 35.17769 35.01187 35.10783 35.06803 34.1475    10   b
 write_feather(flights, "./inst/feather/mt.feather")  1.00000  1.00000  1.00000  1.00000  1.00000  1.0000    10  a 
> microbenchmark(RDS <- readRDS('./inst/feather/mt.rds'), F <- read_feather('./inst/feather/mt.feather'), times = 10L, control = list(order = 'block'), unit = 'relative')

Unit: relative
                                           expr      min      lq    mean   median       uq      max neval cld
        RDS <- readRDS("./inst/feather/mt.rds") 8.143911 8.00167 5.21065 4.746222 4.154454 4.014567    10   b
 F <- read_feather("./inst/feather/mt.feather") 1.000000 1.00000 1.00000 1.000000 1.000000 1.000000    10  a 
> all.equal(F, RDS)
[1] TRUE
```
