### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [wesm/feather#72]
Some parameters (like "[${BUILD_SUPPORT_DIR}/cpplint.py](https://github.com/wesm/feather/blob/ecf4f87a51688103b256b571146166daf02131ac/cpp/CMakeLists.txt#L173)" and "[${OUTPUT_DIR}](https://github.com/wesm/feather/blob/1c09667f131ebe8667b64884fcc3dbf366af7a99/cpp/src/feather/CMakeLists.txt#L75)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](https://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by wesm** [comment]
Can you please submit a patch? Thank you
