### ISSUE TITLE
[feature request] support for user-level metadata

### ISSUE THREAD

**Issue by jreback** [wesm/feather#74]
Idea would be to allow a restricted metadata to be attached globally? per-column? of types that are serializable by `feather`. something like. The usecase I am thinking is to allow pandas to support complete round-tripping.

e.g.

```
In [3]: df = pd.DataFrame({'A' : ['foo','foo','bar'], 'B' : [1,2,3]})

In [4]: df
Out[4]: 
     A  B
0  foo  1
1  foo  2
2  bar  3

In [5]: feather.write_dataframe(df, 'foo.fth')

In [6]: feather.read_dataframe('foo.fth')
Out[6]: 
     A  B
0  foo  1
1  foo  2
2  bar  3

In [7]: feather.read_dataframe('foo.fth').equals(df)
Out[7]: True

In [8]: sdf = df.set_index('A')

In [9]: sdf
Out[9]: 
     B
A     
foo  1
foo  2
bar  3

In [10]: feather.write_dataframe(sdf, 'foo.fth')

In [11]: feather.read_dataframe('foo.fth')
Out[11]: 
   B
0  1
1  2
2  3
```

so on [11] loosing the 'metadata'. But in a pandas wrapper if I could do:

```
feather.write_data_frame(sdf.reset_index(), 'foo.fth', {'index' : ['A']})

df, metadata = feather.read_frame('foo.fth', return_metadata=True)
df = df.set_index(metadata['index'])
```

Then I could round-trip exactly.

HDF5 allows support for _arbitrary_ metadata on the group nodes (it just pickles this). But I think that would be out-of-scope here as its not cross-lang compat.

I think this would nicely solve the representation problem (everything still stored as table likes), but the metadata can offer an alternative interpretation w/o getting in the way of others.

**Comment by jreback** [comment]
another use would be ``{ 'encoding' : 'utf-8' }``

**Comment by shoyer** [comment]
> HDF5 allows support for arbitrary metadata on the group nodes (it just pickles this).

This is not quite right. *pytables* allows for arbitrary metadata by pickling. HDF5 itself allows for attributes with arbitrary datatypes supported by HDF5.

> another use would be { 'encoding' : 'utf-8' }
>
> actually encoding should be baked directly into the string columns.

Strings in Feather are always UTF-8. Which is how it should be.

**Comment by jreback** [comment]
maybe you misunderstand me @shoyer I didn't say that strings should always be UTF-8 I agree they should. What is needed is meta-data that indicates to the reader that this was originally NOT UTF-8 and some other encoding. Otherwise you end up having to carry around additional pieces of meta-data in the user side process. This format then becomes less reproducible / round-trippable.

**Comment by wesm** [comment]
Non-UTF8 strings should be stored at binary columns with metadata indicating the string encoding

**Comment by shoyer** [comment]
OK, yes, this makes sense.

**Comment by ScottPJones** [comment]
I would have hoped that UTF-16 support would also be built in, and not be relegated to being only a user-defined type. For performance, we always use validated Unicode strings, and stored efficiently using either 8-bit or 16-bit codeunits, marked as being either ASCII, ANSI Latin 1 (i.e. 1st 256 codepoints of Unicode), UCS2 (i.e. UTF-16, with only BMP characters, no surrogates), and UTF-16.
(similar to how Python 3.3 and above store strings).  Not having decent UTF-16 support also makes things less performant when dealing with other languages / APIs such as Java or Swift.

**Comment by hadley** [comment]
@ScottPJones you'd be better off starting a new issue to discuss this

**Comment by wesm** [comment]
With Feather V2 coming in Arrow 0.17.0 we support all the metadata storage features that Arrow schemas have, which cover the use cases here I think
