### ISSUE TITLE
Should feather meet blosc/bcolz?

### ISSUE THREAD

**Issue by kzk2000** [wesm/feather#76]
https://github.com/Blosc/bcolz -- amazingly fast compression, best open-source solution I've seen in my work (20mn rows, 40+ columns), possibly a natural extension to add compression to feather...?

**Comment by wesm** [comment]
Yes, I had planned to add c-blosc compression (or lz4, to simplify the build and packaging problem) as a simple overlay. IIRC there's size limitation to compressed chunks, and we probably want to add some chunking to the compression anyway, so worth keeping that in mind.

**Comment by wesm** [comment]
See ARROW-300. I would like to add a blocked compression option to the Arrow IPC format, which would be relatively trivial to integrate into Feather. I suggest we explore this work there

**Comment by ostrokach** [comment]
Link for anyone interested: https://issues.apache.org/jira/browse/ARROW-300.
