### ISSUE TITLE
Fatal error when the path is wrong (R)

### ISSUE THREAD

**Issue by pachevalier** [wesm/feather#80]
I've tried to run the following program : 

    library(feather)
    x <- runif(1e7)
    x[sample(1e7, 1e6)] <- NA # 10% NAs
   df <- as.data.frame(replicate(10, x))
   write_feather(df, path = 'data/test.feather')

If the data directory doesn't exist, I've got a fatal error : 

![capture du 2016-04-01 15-23-39](https://cloud.githubusercontent.com/assets/3227753/14208159/3fb39bfa-f81e-11e5-962d-5ed33617aec1.png)

If I run try to export the file to a csv, I've got a simple error : 

    > library(readr)
    > write_csv(df, path = 'data/test.feather')
    Erreur : Failed to open 'data/test.feather'.

It would be nice to have the same kind of message with feather.

**Comment by hadley** [comment]
Minimal reprex:

```R
write_feather(data.frame(x = 1:10), 'asfsdfsdafd/test.feather')
```

**Comment by hadley** [comment]
@wesm this is coming from `FileOutputStream::Open()`. I think you need to check that `file_` is not null before calling `ferror()`

**Comment by pachevalier** [comment]
Nice It works !!
