### ISSUE TITLE
Fatal error writing a feather file

### ISSUE THREAD

**Issue by pachevalier** [wesm/feather#81]
I've tried to write a feather file with a real example. I've downloaded one of the csv file of the OpenDamir dataset distributed by Data.Gouv.fr

    # download and gunzip : https://www.data.gouv.fr/s/resources/cnamts/P201412.csv.gz
    library(readr)
    library(feather)
    df <- read_csv2("data/P201412.csv")
    write_feather(df, path = "data/opendamir.feather")

I've got a fatal error when writing the feather file.

**Comment by hadley** [comment]
Could you please try reproducing with a smaller example?

**Comment by pachevalier** [comment]
Here is an example with a BANO file (French national address database with only 280,000 rows). I don't have the same error but I'm unable to read the feather file : 

    > library(readr)
    > library(feather)
    > # wget http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl_01-csv.bz2
    > df <- read_csv("data/BAN_odbl_01-csv.bz2")
    > write_feather(df, "data/bano_01.feather")
    > system.time(read_csv("data/BAN_odbl_01-csv.bz2"))
    utilisateur     système      écoulé 
      2.067       0.063       2.132 
    > system.time(read_feather('data/test.feather'))
    Error in normalizePath(path, mustWork = TRUE) : 
  path[1]="data/test.feather": No such file or directory
   Timing stopped at: 0.001 0 0.001

**Comment by hadley** [comment]
You need to read the same file that you wrote:

```R
write_feather(df, "data/bano_01.feather")
# ...
read_feather('data/test.feather')
```
