### ISSUE TITLE
Use cmake ExternalProject instead of a shell script for building thirdparty?

### ISSUE THREAD

**Issue by tkelman** [wesm/feather#88]
This could probably be cleaner in cases like cross compilation where you may need to pass lots of complicated cmake flags to the main project as well as the deps. Patching up a shell script is never fun. Thoughts?

**Comment by wesm** [comment]
I believe this only works when all the thirdparty dependencies use cmake. Not an issue right now, but may become one in the future?

**Comment by tkelman** [comment]
Pretty sure you can specify custom non-cmake configuration and build commands, ref http://stackoverflow.com/questions/5971921/building-a-library-using-autotools-from-cmake. Though that would re-introduce the same flag-passing/translation issue.

**Comment by wesm** [comment]
This is addressed in the Apache Arrow C++ codebase
